'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.3/WebService/B2B/GeneralB2BService.asmx")>  _
        Public ReadOnly Property WinTexDLL_GeneralB2B_GeneralB2BService() As String
            Get
                Return CType(Me("WinTexDLL_GeneralB2B_GeneralB2BService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.3/WebService/General/GeneralSenfoniService.asmx")>  _
        Public ReadOnly Property WinTexDLL_UyumsoftGeneralSenfoniService_GeneralSenfoniService() As String
            Get
                Return CType(Me("WinTexDLL_UyumsoftGeneralSenfoniService_GeneralSenfoniService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.3/WebService/ERP/UyumGetWebService.asmx")>  _
        Public ReadOnly Property WinTexDLL_UyumsoftGetWEBService_UyumGetWebService() As String
            Get
                Return CType(Me("WinTexDLL_UyumsoftGetWEBService_UyumGetWebService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.3/WebService/ERP/UyumSaveWebService.asmx")>  _
        Public ReadOnly Property WinTexDLL_UyumsoftSaveWebService_UyumSaveWebService() As String
            Get
                Return CType(Me("WinTexDLL_UyumsoftSaveWebService_UyumSaveWebService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.3/webservice/eroglu/ErogluProduction.asmx")>  _
        Public ReadOnly Property WinTexDLL_UyumErogluProduction_ErogluProduction() As String
            Get
                Return CType(Me("WinTexDLL_UyumErogluProduction_ErogluProduction"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.3/webservice/uyumwebservice.asmx")>  _
        Public ReadOnly Property WinTexDLL_UyumWebService_UyumWebService() As String
            Get
                Return CType(Me("WinTexDLL_UyumWebService_UyumWebService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Select * from siparis")>  _
        Public ReadOnly Property SQL1() As String
            Get
                Return CType(Me("SQL1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=msi;Initial Catalog=TES;Persist Security Info=True;User ID=sa;Passwor"& _ 
            "d=Hayabusa1024")>  _
        Public ReadOnly Property TESConnectionString() As String
            Get
                Return CType(Me("TESConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://efinttestws.turkkep.com.tr/EFaturaEntegrasyon2.asmx")>  _
        Public ReadOnly Property WinTexDLL_tr_com_turkkep_efinttestws_EFaturaEntegrasyon2() As String
            Get
                Return CType(Me("WinTexDLL_tr_com_turkkep_efinttestws_EFaturaEntegrasyon2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wstesteirsaliye.edoksis.net/IrsaliyeWebService.asmx")>  _
        Public ReadOnly Property WinTexDLL_net_edoksis_efaturatest_IrsaliyeWebService() As String
            Get
                Return CType(Me("WinTexDLL_net_edoksis_efaturatest_IrsaliyeWebService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wstest.parkentegrasyon.com.tr/EFaturaIntegration.asmx")>  _
        Public ReadOnly Property WinTexDLL_tr_com_parkentegrasyon_wstest_EFaturaIntegration() As String
            Get
                Return CType(Me("WinTexDLL_tr_com_parkentegrasyon_wstest_EFaturaIntegration"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WinTexDLL.My.MySettings
            Get
                Return Global.WinTexDLL.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
