'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ArasService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CallCourierReturn", [Namespace]:="http://schemas.datacontract.org/2004/07/CustCargoInfo.Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CallCourierReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private countField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private resultField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private resultMessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property count() As Integer
            Get
                Return Me.countField
            End Get
            Set
                If (Me.countField.Equals(value) <> true) Then
                    Me.countField = value
                    Me.RaisePropertyChanged("count")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property result() As Integer
            Get
                Return Me.resultField
            End Get
            Set
                If (Me.resultField.Equals(value) <> true) Then
                    Me.resultField = value
                    Me.RaisePropertyChanged("result")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property resultMessage() As String
            Get
                Return Me.resultMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.resultMessageField, value) <> true) Then
                    Me.resultMessageField = value
                    Me.RaisePropertyChanged("resultMessage")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ArasService.IArasCargoIntegrationService", SessionMode:=System.ServiceModel.SessionMode.NotAllowed)>  _
    Public Interface IArasCargoIntegrationService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/GetQueryDS", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/GetQueryDSResponse")>  _
        Function GetQueryDS(ByVal loginInfo As String, ByVal queryInfo As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/GetQueryDS", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/GetQueryDSResponse")>  _
        Function GetQueryDSAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/GetQueryXML", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/GetQueryXMLResponse")>  _
        Function GetQueryXML(ByVal loginInfo As String, ByVal queryInfo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/GetQueryXML", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/GetQueryXMLResponse")>  _
        Function GetQueryXMLAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/GetQueryJSON", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/GetQueryJSONResponse")>  _
        Function GetQueryJSON(ByVal loginInfo As String, ByVal queryInfo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/GetQueryJSON", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/GetQueryJSONResponse")>  _
        Function GetQueryJSONAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/SetDataXML", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/SetDataXMLResponse")>  _
        Function SetDataXML(ByVal loginInfo As String, ByVal queryInfo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/SetDataXML", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/SetDataXMLResponse")>  _
        Function SetDataXMLAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/CallCourier", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/CallCourierResponse")>  _
        Function CallCourier(ByVal loginInfo As String, ByVal queryInfo As String) As ArasService.CallCourierReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArasCargoIntegrationService/CallCourier", ReplyAction:="http://tempuri.org/IArasCargoIntegrationService/CallCourierResponse")>  _
        Function CallCourierAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of ArasService.CallCourierReturn)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IArasCargoIntegrationServiceChannel
        Inherits ArasService.IArasCargoIntegrationService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ArasCargoIntegrationServiceClient
        Inherits System.ServiceModel.ClientBase(Of ArasService.IArasCargoIntegrationService)
        Implements ArasService.IArasCargoIntegrationService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetQueryDS(ByVal loginInfo As String, ByVal queryInfo As String) As System.Data.DataSet Implements ArasService.IArasCargoIntegrationService.GetQueryDS
            Return MyBase.Channel.GetQueryDS(loginInfo, queryInfo)
        End Function
        
        Public Function GetQueryDSAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ArasService.IArasCargoIntegrationService.GetQueryDSAsync
            Return MyBase.Channel.GetQueryDSAsync(loginInfo, queryInfo)
        End Function
        
        Public Function GetQueryXML(ByVal loginInfo As String, ByVal queryInfo As String) As String Implements ArasService.IArasCargoIntegrationService.GetQueryXML
            Return MyBase.Channel.GetQueryXML(loginInfo, queryInfo)
        End Function
        
        Public Function GetQueryXMLAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of String) Implements ArasService.IArasCargoIntegrationService.GetQueryXMLAsync
            Return MyBase.Channel.GetQueryXMLAsync(loginInfo, queryInfo)
        End Function
        
        Public Function GetQueryJSON(ByVal loginInfo As String, ByVal queryInfo As String) As String Implements ArasService.IArasCargoIntegrationService.GetQueryJSON
            Return MyBase.Channel.GetQueryJSON(loginInfo, queryInfo)
        End Function
        
        Public Function GetQueryJSONAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of String) Implements ArasService.IArasCargoIntegrationService.GetQueryJSONAsync
            Return MyBase.Channel.GetQueryJSONAsync(loginInfo, queryInfo)
        End Function
        
        Public Function SetDataXML(ByVal loginInfo As String, ByVal queryInfo As String) As String Implements ArasService.IArasCargoIntegrationService.SetDataXML
            Return MyBase.Channel.SetDataXML(loginInfo, queryInfo)
        End Function
        
        Public Function SetDataXMLAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of String) Implements ArasService.IArasCargoIntegrationService.SetDataXMLAsync
            Return MyBase.Channel.SetDataXMLAsync(loginInfo, queryInfo)
        End Function
        
        Public Function CallCourier(ByVal loginInfo As String, ByVal queryInfo As String) As ArasService.CallCourierReturn Implements ArasService.IArasCargoIntegrationService.CallCourier
            Return MyBase.Channel.CallCourier(loginInfo, queryInfo)
        End Function
        
        Public Function CallCourierAsync(ByVal loginInfo As String, ByVal queryInfo As String) As System.Threading.Tasks.Task(Of ArasService.CallCourierReturn) Implements ArasService.IArasCargoIntegrationService.CallCourierAsync
            Return MyBase.Channel.CallCourierAsync(loginInfo, queryInfo)
        End Function
    End Class
End Namespace
