'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace UWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="UyumWebServiceSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(WhereClause()))>  _
    Partial Public Class UyumWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetTableValuesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDataTableWithSQLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTableValuesWithPermissionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetObjectToDataSetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetObjectWSDLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InsertDataSetToCollectionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InsertDataSetToCollection2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateDataSetToCollectionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteObjectOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateObjectOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateInvoiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UyumGateway.My.MySettings.Default.UyumGateway_UWS_UyumWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetTableValuesCompleted As GetTableValuesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDataTableWithSQLCompleted As GetDataTableWithSQLCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTableValuesWithPermissionCompleted As GetTableValuesWithPermissionCompletedEventHandler
        
        '''<remarks/>
        Public Event GetObjectToDataSetCompleted As GetObjectToDataSetCompletedEventHandler
        
        '''<remarks/>
        Public Event GetObjectWSDLCompleted As GetObjectWSDLCompletedEventHandler
        
        '''<remarks/>
        Public Event InsertDataSetToCollectionCompleted As InsertDataSetToCollectionCompletedEventHandler
        
        '''<remarks/>
        Public Event InsertDataSetToCollection2Completed As InsertDataSetToCollection2CompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateDataSetToCollectionCompleted As UpdateDataSetToCollectionCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteObjectCompleted As DeleteObjectCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateObjectCompleted As UpdateObjectCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateInvoiceCompleted As UpdateInvoiceCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTableValues", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTableValues(ByVal Context As UyumServiceRequestOfTableInfoIn) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("GetTableValues", New Object() {Context})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTableValuesAsync(ByVal Context As UyumServiceRequestOfTableInfoIn)
            Me.GetTableValuesAsync(Context, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTableValuesAsync(ByVal Context As UyumServiceRequestOfTableInfoIn, ByVal userState As Object)
            If (Me.GetTableValuesOperationCompleted Is Nothing) Then
                Me.GetTableValuesOperationCompleted = AddressOf Me.OnGetTableValuesOperationCompleted
            End If
            Me.InvokeAsync("GetTableValues", New Object() {Context}, Me.GetTableValuesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTableValuesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTableValuesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTableValuesCompleted(Me, New GetTableValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataTableWithSQL", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDataTableWithSQL(ByVal Context As UyumServiceRequestOfString) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("GetDataTableWithSQL", New Object() {Context})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDataTableWithSQLAsync(ByVal Context As UyumServiceRequestOfString)
            Me.GetDataTableWithSQLAsync(Context, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDataTableWithSQLAsync(ByVal Context As UyumServiceRequestOfString, ByVal userState As Object)
            If (Me.GetDataTableWithSQLOperationCompleted Is Nothing) Then
                Me.GetDataTableWithSQLOperationCompleted = AddressOf Me.OnGetDataTableWithSQLOperationCompleted
            End If
            Me.InvokeAsync("GetDataTableWithSQL", New Object() {Context}, Me.GetDataTableWithSQLOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDataTableWithSQLOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDataTableWithSQLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDataTableWithSQLCompleted(Me, New GetDataTableWithSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTableValuesWithPermission", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTableValuesWithPermission(ByVal Context As UyumServiceRequestOfTableInfoIn) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("GetTableValuesWithPermission", New Object() {Context})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTableValuesWithPermissionAsync(ByVal Context As UyumServiceRequestOfTableInfoIn)
            Me.GetTableValuesWithPermissionAsync(Context, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTableValuesWithPermissionAsync(ByVal Context As UyumServiceRequestOfTableInfoIn, ByVal userState As Object)
            If (Me.GetTableValuesWithPermissionOperationCompleted Is Nothing) Then
                Me.GetTableValuesWithPermissionOperationCompleted = AddressOf Me.OnGetTableValuesWithPermissionOperationCompleted
            End If
            Me.InvokeAsync("GetTableValuesWithPermission", New Object() {Context}, Me.GetTableValuesWithPermissionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTableValuesWithPermissionOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTableValuesWithPermissionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTableValuesWithPermissionCompleted(Me, New GetTableValuesWithPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetObjectToDataSet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetObjectToDataSet(ByVal Context As UyumServiceRequestOfObjectInfoIn) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetObjectToDataSet", New Object() {Context})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetObjectToDataSetAsync(ByVal Context As UyumServiceRequestOfObjectInfoIn)
            Me.GetObjectToDataSetAsync(Context, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetObjectToDataSetAsync(ByVal Context As UyumServiceRequestOfObjectInfoIn, ByVal userState As Object)
            If (Me.GetObjectToDataSetOperationCompleted Is Nothing) Then
                Me.GetObjectToDataSetOperationCompleted = AddressOf Me.OnGetObjectToDataSetOperationCompleted
            End If
            Me.InvokeAsync("GetObjectToDataSet", New Object() {Context}, Me.GetObjectToDataSetOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetObjectToDataSetOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetObjectToDataSetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetObjectToDataSetCompleted(Me, New GetObjectToDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetObjectWSDL", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetObjectWSDL(ByVal Context As UyumServiceRequestOfString) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetObjectWSDL", New Object() {Context})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetObjectWSDLAsync(ByVal Context As UyumServiceRequestOfString)
            Me.GetObjectWSDLAsync(Context, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetObjectWSDLAsync(ByVal Context As UyumServiceRequestOfString, ByVal userState As Object)
            If (Me.GetObjectWSDLOperationCompleted Is Nothing) Then
                Me.GetObjectWSDLOperationCompleted = AddressOf Me.OnGetObjectWSDLOperationCompleted
            End If
            Me.InvokeAsync("GetObjectWSDL", New Object() {Context}, Me.GetObjectWSDLOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetObjectWSDLOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetObjectWSDLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetObjectWSDLCompleted(Me, New GetObjectWSDLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertDataSetToCollection", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InsertDataSetToCollection(ByVal Context As UyumServiceRequestOfDataSet) As Integer
            Dim results() As Object = Me.Invoke("InsertDataSetToCollection", New Object() {Context})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InsertDataSetToCollectionAsync(ByVal Context As UyumServiceRequestOfDataSet)
            Me.InsertDataSetToCollectionAsync(Context, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertDataSetToCollectionAsync(ByVal Context As UyumServiceRequestOfDataSet, ByVal userState As Object)
            If (Me.InsertDataSetToCollectionOperationCompleted Is Nothing) Then
                Me.InsertDataSetToCollectionOperationCompleted = AddressOf Me.OnInsertDataSetToCollectionOperationCompleted
            End If
            Me.InvokeAsync("InsertDataSetToCollection", New Object() {Context}, Me.InsertDataSetToCollectionOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertDataSetToCollectionOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertDataSetToCollectionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertDataSetToCollectionCompleted(Me, New InsertDataSetToCollectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertDataSetToCollection2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InsertDataSetToCollection2(ByVal Context As UyumServiceRequestOfDataSet, ByVal DisableAutoIncrement As Boolean) As Integer
            Dim results() As Object = Me.Invoke("InsertDataSetToCollection2", New Object() {Context, DisableAutoIncrement})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InsertDataSetToCollection2Async(ByVal Context As UyumServiceRequestOfDataSet, ByVal DisableAutoIncrement As Boolean)
            Me.InsertDataSetToCollection2Async(Context, DisableAutoIncrement, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertDataSetToCollection2Async(ByVal Context As UyumServiceRequestOfDataSet, ByVal DisableAutoIncrement As Boolean, ByVal userState As Object)
            If (Me.InsertDataSetToCollection2OperationCompleted Is Nothing) Then
                Me.InsertDataSetToCollection2OperationCompleted = AddressOf Me.OnInsertDataSetToCollection2OperationCompleted
            End If
            Me.InvokeAsync("InsertDataSetToCollection2", New Object() {Context, DisableAutoIncrement}, Me.InsertDataSetToCollection2OperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertDataSetToCollection2OperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertDataSetToCollection2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertDataSetToCollection2Completed(Me, New InsertDataSetToCollection2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateDataSetToCollection", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateDataSetToCollection(ByVal Context As UyumServiceRequestOfDataSet, ByVal DisableAutoIncrement As Boolean) As Integer
            Dim results() As Object = Me.Invoke("UpdateDataSetToCollection", New Object() {Context, DisableAutoIncrement})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateDataSetToCollectionAsync(ByVal Context As UyumServiceRequestOfDataSet, ByVal DisableAutoIncrement As Boolean)
            Me.UpdateDataSetToCollectionAsync(Context, DisableAutoIncrement, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateDataSetToCollectionAsync(ByVal Context As UyumServiceRequestOfDataSet, ByVal DisableAutoIncrement As Boolean, ByVal userState As Object)
            If (Me.UpdateDataSetToCollectionOperationCompleted Is Nothing) Then
                Me.UpdateDataSetToCollectionOperationCompleted = AddressOf Me.OnUpdateDataSetToCollectionOperationCompleted
            End If
            Me.InvokeAsync("UpdateDataSetToCollection", New Object() {Context, DisableAutoIncrement}, Me.UpdateDataSetToCollectionOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateDataSetToCollectionOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateDataSetToCollectionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateDataSetToCollectionCompleted(Me, New UpdateDataSetToCollectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteObject", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteObject(ByVal Context As UyumServiceRequestOfObjectDeleteIn) As String
            Dim results() As Object = Me.Invoke("DeleteObject", New Object() {Context})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteObjectAsync(ByVal Context As UyumServiceRequestOfObjectDeleteIn)
            Me.DeleteObjectAsync(Context, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteObjectAsync(ByVal Context As UyumServiceRequestOfObjectDeleteIn, ByVal userState As Object)
            If (Me.DeleteObjectOperationCompleted Is Nothing) Then
                Me.DeleteObjectOperationCompleted = AddressOf Me.OnDeleteObjectOperationCompleted
            End If
            Me.InvokeAsync("DeleteObject", New Object() {Context}, Me.DeleteObjectOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteObjectOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteObjectCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteObjectCompleted(Me, New DeleteObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateObject", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateObject(ByVal Context As UyumServiceRequestOfObjectsIn) As Boolean
            Dim results() As Object = Me.Invoke("UpdateObject", New Object() {Context})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateObjectAsync(ByVal Context As UyumServiceRequestOfObjectsIn)
            Me.UpdateObjectAsync(Context, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateObjectAsync(ByVal Context As UyumServiceRequestOfObjectsIn, ByVal userState As Object)
            If (Me.UpdateObjectOperationCompleted Is Nothing) Then
                Me.UpdateObjectOperationCompleted = AddressOf Me.OnUpdateObjectOperationCompleted
            End If
            Me.InvokeAsync("UpdateObject", New Object() {Context}, Me.UpdateObjectOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateObjectOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateObjectCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateObjectCompleted(Me, New UpdateObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateInvoice", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateInvoice(ByVal Context As UyumServiceRequestOfInt32) As Boolean
            Dim results() As Object = Me.Invoke("UpdateInvoice", New Object() {Context})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateInvoiceAsync(ByVal Context As UyumServiceRequestOfInt32)
            Me.UpdateInvoiceAsync(Context, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateInvoiceAsync(ByVal Context As UyumServiceRequestOfInt32, ByVal userState As Object)
            If (Me.UpdateInvoiceOperationCompleted Is Nothing) Then
                Me.UpdateInvoiceOperationCompleted = AddressOf Me.OnUpdateInvoiceOperationCompleted
            End If
            Me.InvokeAsync("UpdateInvoice", New Object() {Context}, Me.UpdateInvoiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateInvoiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateInvoiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateInvoiceCompleted(Me, New UpdateInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UyumServiceRequestOfTableInfoIn
        
        Private tokenField As UyumToken
        
        Private valueField As TableInfoIn
        
        Private topField As Integer
        
        '''<remarks/>
        Public Property Token() As UyumToken
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As TableInfoIn
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Top() As Integer
            Get
                Return Me.topField
            End Get
            Set
                Me.topField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UyumToken
        
        Private userNameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UyumServiceRequestOfInt32
        
        Private tokenField As UyumToken
        
        Private valueField As Integer
        
        Private topField As Integer
        
        '''<remarks/>
        Public Property Token() As UyumToken
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Integer
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Top() As Integer
            Get
                Return Me.topField
            End Get
            Set
                Me.topField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObjectsIn
        
        Private objectCollectionTypeNameField As String
        
        Private idField As Integer
        
        '''<remarks/>
        Public Property ObjectCollectionTypeName() As String
            Get
                Return Me.objectCollectionTypeNameField
            End Get
            Set
                Me.objectCollectionTypeNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UyumServiceRequestOfObjectsIn
        
        Private tokenField As UyumToken
        
        Private valueField As ObjectsIn
        
        Private topField As Integer
        
        '''<remarks/>
        Public Property Token() As UyumToken
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As ObjectsIn
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Top() As Integer
            Get
                Return Me.topField
            End Get
            Set
                Me.topField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObjectDeleteIn
        
        Private objectCollectionTypeNameField As String
        
        Private idField As Integer
        
        Private promptValueField As Integer
        
        '''<remarks/>
        Public Property ObjectCollectionTypeName() As String
            Get
                Return Me.objectCollectionTypeNameField
            End Get
            Set
                Me.objectCollectionTypeNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PromptValue() As Integer
            Get
                Return Me.promptValueField
            End Get
            Set
                Me.promptValueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UyumServiceRequestOfObjectDeleteIn
        
        Private tokenField As UyumToken
        
        Private valueField As ObjectDeleteIn
        
        Private topField As Integer
        
        '''<remarks/>
        Public Property Token() As UyumToken
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As ObjectDeleteIn
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Top() As Integer
            Get
                Return Me.topField
            End Get
            Set
                Me.topField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UyumServiceRequestOfDataSet
        
        Private tokenField As UyumToken
        
        Private valueField As System.Data.DataSet
        
        Private topField As Integer
        
        '''<remarks/>
        Public Property Token() As UyumToken
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As System.Data.DataSet
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Top() As Integer
            Get
                Return Me.topField
            End Get
            Set
                Me.topField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WherePropertyClause
        
        Private propertyNameField As String
        
        Private valueField As Object
        
        '''<remarks/>
        Public Property PropertyName() As String
            Get
                Return Me.propertyNameField
            End Get
            Set
                Me.propertyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObjectInfoIn
        
        Private objectCollectionTypeNameField As String
        
        Private loadDetailField As Boolean
        
        Private whereClauseListField() As WherePropertyClause
        
        '''<remarks/>
        Public Property ObjectCollectionTypeName() As String
            Get
                Return Me.objectCollectionTypeNameField
            End Get
            Set
                Me.objectCollectionTypeNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LoadDetail() As Boolean
            Get
                Return Me.loadDetailField
            End Get
            Set
                Me.loadDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WhereClauseList() As WherePropertyClause()
            Get
                Return Me.whereClauseListField
            End Get
            Set
                Me.whereClauseListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UyumServiceRequestOfObjectInfoIn
        
        Private tokenField As UyumToken
        
        Private valueField As ObjectInfoIn
        
        Private topField As Integer
        
        '''<remarks/>
        Public Property Token() As UyumToken
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As ObjectInfoIn
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Top() As Integer
            Get
                Return Me.topField
            End Get
            Set
                Me.topField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UyumServiceRequestOfString
        
        Private tokenField As UyumToken
        
        Private valueField As String
        
        Private topField As Integer
        
        '''<remarks/>
        Public Property Token() As UyumToken
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Top() As Integer
            Get
                Return Me.topField
            End Get
            Set
                Me.topField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WhereClause
        
        Private fieldNameField As String
        
        Private valueField As Object
        
        Private operatorField As String
        
        Private dTypeField As DbType
        
        '''<remarks/>
        Public Property FieldName() As String
            Get
                Return Me.fieldNameField
            End Get
            Set
                Me.fieldNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Operator]() As String
            Get
                Return Me.operatorField
            End Get
            Set
                Me.operatorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DType() As DbType
            Get
                Return Me.dTypeField
            End Get
            Set
                Me.dTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum DbType
        
        '''<remarks/>
        AnsiString
        
        '''<remarks/>
        Binary
        
        '''<remarks/>
        [Byte]
        
        '''<remarks/>
        [Boolean]
        
        '''<remarks/>
        Currency
        
        '''<remarks/>
        [Date]
        
        '''<remarks/>
        DateTime
        
        '''<remarks/>
        [Decimal]
        
        '''<remarks/>
        [Double]
        
        '''<remarks/>
        Guid
        
        '''<remarks/>
        Int16
        
        '''<remarks/>
        Int32
        
        '''<remarks/>
        Int64
        
        '''<remarks/>
        [Object]
        
        '''<remarks/>
        [SByte]
        
        '''<remarks/>
        [Single]
        
        '''<remarks/>
        [String]
        
        '''<remarks/>
        Time
        
        '''<remarks/>
        UInt16
        
        '''<remarks/>
        UInt32
        
        '''<remarks/>
        UInt64
        
        '''<remarks/>
        VarNumeric
        
        '''<remarks/>
        AnsiStringFixedLength
        
        '''<remarks/>
        StringFixedLength
        
        '''<remarks/>
        Xml
        
        '''<remarks/>
        DateTime2
        
        '''<remarks/>
        DateTimeOffset
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class TableInfoIn
        
        Private tableNameField As String
        
        Private whereClauseListField() As WhereClause
        
        '''<remarks/>
        Public Property TableName() As String
            Get
                Return Me.tableNameField
            End Get
            Set
                Me.tableNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WhereClauseList() As WhereClause()
            Get
                Return Me.whereClauseListField
            End Get
            Set
                Me.whereClauseListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetTableValuesCompletedEventHandler(ByVal sender As Object, ByVal e As GetTableValuesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTableValuesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetDataTableWithSQLCompletedEventHandler(ByVal sender As Object, ByVal e As GetDataTableWithSQLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDataTableWithSQLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetTableValuesWithPermissionCompletedEventHandler(ByVal sender As Object, ByVal e As GetTableValuesWithPermissionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTableValuesWithPermissionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetObjectToDataSetCompletedEventHandler(ByVal sender As Object, ByVal e As GetObjectToDataSetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetObjectToDataSetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetObjectWSDLCompletedEventHandler(ByVal sender As Object, ByVal e As GetObjectWSDLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetObjectWSDLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub InsertDataSetToCollectionCompletedEventHandler(ByVal sender As Object, ByVal e As InsertDataSetToCollectionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InsertDataSetToCollectionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub InsertDataSetToCollection2CompletedEventHandler(ByVal sender As Object, ByVal e As InsertDataSetToCollection2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InsertDataSetToCollection2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub UpdateDataSetToCollectionCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateDataSetToCollectionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateDataSetToCollectionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub DeleteObjectCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteObjectCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteObjectCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub UpdateObjectCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateObjectCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateObjectCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub UpdateInvoiceCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateInvoiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateInvoiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
