'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace mngiade
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="mngiade.MusteriSiparisNewSoap")>  _
    Public Interface MusteriSiparisNewSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SiparisKayit_C2C", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SiparisKayit_C2C( _
                    ByVal pKullaniciAdi As String,  _
                    ByVal pSifre As String,  _
                    ByVal pSiparisNo As String,  _
                    ByVal pBarkodText As String,  _
                    ByVal pIrsaliyeNo As String,  _
                    ByVal pUrunBedeli As String,  _
                    ByVal pGonderiParcaList() As mngiade.GonderiParca,  _
                    ByVal pGonderenMusteri As mngiade.Gonderici,  _
                    ByVal pAliciMusteri As mngiade.Alici,  _
                    ByVal pOdemeSekli As mngiade.OdemeSekli,  _
                    ByVal pTeslimSekli As mngiade.TeslimSekli,  _
                    ByVal pKargoCinsi As mngiade.KargoCinsi,  _
                    ByVal pGonSms As mngiade.GondericiSms,  _
                    ByVal pAliciSms As mngiade.AliciSms,  _
                    ByVal pKapidaTahsilat As mngiade.KapidaOdeme,  _
                    ByVal pAciklama As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SiparisKayit_C2C", ReplyAction:="*")>  _
        Function SiparisKayit_C2CAsync( _
                    ByVal pKullaniciAdi As String,  _
                    ByVal pSifre As String,  _
                    ByVal pSiparisNo As String,  _
                    ByVal pBarkodText As String,  _
                    ByVal pIrsaliyeNo As String,  _
                    ByVal pUrunBedeli As String,  _
                    ByVal pGonderiParcaList() As mngiade.GonderiParca,  _
                    ByVal pGonderenMusteri As mngiade.Gonderici,  _
                    ByVal pAliciMusteri As mngiade.Alici,  _
                    ByVal pOdemeSekli As mngiade.OdemeSekli,  _
                    ByVal pTeslimSekli As mngiade.TeslimSekli,  _
                    ByVal pKargoCinsi As mngiade.KargoCinsi,  _
                    ByVal pGonSms As mngiade.GondericiSms,  _
                    ByVal pAliciSms As mngiade.AliciSms,  _
                    ByVal pKapidaTahsilat As mngiade.KapidaOdeme,  _
                    ByVal pAciklama As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SiparisKayit_B2B", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SiparisKayit_B2B(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pGondericiMngMusNo As String, ByVal pGondericiMusRefNo As String, ByVal pAliciMngMusNo As String, ByVal pAliciMusRefNo As String, ByVal pOtherParam() As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SiparisKayit_B2B", ReplyAction:="*")>  _
        Function SiparisKayit_B2BAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pGondericiMngMusNo As String, ByVal pGondericiMusRefNo As String, ByVal pAliciMngMusNo As String, ByVal pAliciMusRefNo As String, ByVal pOtherParam() As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SiparisIptali_C2C", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SiparisIptali_C2C(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SiparisIptali_C2C", ReplyAction:="*")>  _
        Function SiparisIptali_C2CAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GelecekIadeSiparisKayit", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GelecekIadeSiparisKayit(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GelecekIadeSiparisKayit", ReplyAction:="*")>  _
        Function GelecekIadeSiparisKayitAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GelecekGonderiKayit", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GelecekGonderiKayit(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GelecekGonderiKayit", ReplyAction:="*")>  _
        Function GelecekGonderiKayitAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GelecekIadeSiparisIptali", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GelecekIadeSiparisIptali(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GelecekIadeSiparisIptali", ReplyAction:="*")>  _
        Function GelecekIadeSiparisIptaliAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GelecekIadeSiparisKontrol", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GelecekIadeSiparisKontrol(ByVal pRfSipGnMusteriNo As String, ByVal pRfSipGnMusteriSifre As String, ByVal pChBarkod As String, ByVal pChFaturaSeri As String, ByVal pChFaturaNo As String, ByVal pNmGonderiNo As String, ByVal pChSiparisNo As String, ByVal pGonderiCikisTarihi As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GelecekIadeSiparisKontrol", ReplyAction:="*")>  _
        Function GelecekIadeSiparisKontrolAsync(ByVal pRfSipGnMusteriNo As String, ByVal pRfSipGnMusteriSifre As String, ByVal pChBarkod As String, ByVal pChFaturaSeri As String, ByVal pChFaturaNo As String, ByVal pNmGonderiNo As String, ByVal pChSiparisNo As String, ByVal pGonderiCikisTarihi As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AdrestenAlimSiparisKayit", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AdrestenAlimSiparisKayit(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pAlimsekli As mngiade.AlimSekli, ByVal pAlimIstekTarihi As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pAliciMusteri As mngiade.Alici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AdrestenAlimSiparisKayit", ReplyAction:="*")>  _
        Function AdrestenAlimSiparisKayitAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pAlimsekli As mngiade.AlimSekli, ByVal pAlimIstekTarihi As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pAliciMusteri As mngiade.Alici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GonderiParca
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private kgField As Integer
        
        Private desiField As Integer
        
        Private adetField As Integer
        
        Private icerikField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Kg() As Integer
            Get
                Return Me.kgField
            End Get
            Set
                Me.kgField = value
                Me.RaisePropertyChanged("Kg")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Desi() As Integer
            Get
                Return Me.desiField
            End Get
            Set
                Me.desiField = value
                Me.RaisePropertyChanged("Desi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Adet() As Integer
            Get
                Return Me.adetField
            End Get
            Set
                Me.adetField = value
                Me.RaisePropertyChanged("Adet")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Icerik() As String
            Get
                Return Me.icerikField
            End Get
            Set
                Me.icerikField = value
                Me.RaisePropertyChanged("Icerik")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Alici
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pAliciMusteriMngNoField As String
        
        Private pAliciMusteriBayiNoField As String
        
        Private pAliciMusteriAdiField As String
        
        Private pAliciMusAdresFarkliField As String
        
        Private pAliciIlAdiField As String
        
        Private pAliciilceAdiField As String
        
        Private pAliciAdresTextField As String
        
        Private pAliciSemtField As String
        
        Private pAliciMahalleField As String
        
        Private pAliciMeydanBulvarField As String
        
        Private pAliciCaddeField As String
        
        Private pAliciSokakField As String
        
        Private pAliciTelIsField As String
        
        Private pAliciTelEvField As String
        
        Private pAliciTelCepField As String
        
        Private pAliciFaxField As String
        
        Private pAliciEmailField As String
        
        Private pAliciVergiDairesiField As String
        
        Private pAliciVergiNumarasiField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property pAliciMusteriMngNo() As String
            Get
                Return Me.pAliciMusteriMngNoField
            End Get
            Set
                Me.pAliciMusteriMngNoField = value
                Me.RaisePropertyChanged("pAliciMusteriMngNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property pAliciMusteriBayiNo() As String
            Get
                Return Me.pAliciMusteriBayiNoField
            End Get
            Set
                Me.pAliciMusteriBayiNoField = value
                Me.RaisePropertyChanged("pAliciMusteriBayiNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property pAliciMusteriAdi() As String
            Get
                Return Me.pAliciMusteriAdiField
            End Get
            Set
                Me.pAliciMusteriAdiField = value
                Me.RaisePropertyChanged("pAliciMusteriAdi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property pAliciMusAdresFarkli() As String
            Get
                Return Me.pAliciMusAdresFarkliField
            End Get
            Set
                Me.pAliciMusAdresFarkliField = value
                Me.RaisePropertyChanged("pAliciMusAdresFarkli")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property pAliciIlAdi() As String
            Get
                Return Me.pAliciIlAdiField
            End Get
            Set
                Me.pAliciIlAdiField = value
                Me.RaisePropertyChanged("pAliciIlAdi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property pAliciilceAdi() As String
            Get
                Return Me.pAliciilceAdiField
            End Get
            Set
                Me.pAliciilceAdiField = value
                Me.RaisePropertyChanged("pAliciilceAdi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property pAliciAdresText() As String
            Get
                Return Me.pAliciAdresTextField
            End Get
            Set
                Me.pAliciAdresTextField = value
                Me.RaisePropertyChanged("pAliciAdresText")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property pAliciSemt() As String
            Get
                Return Me.pAliciSemtField
            End Get
            Set
                Me.pAliciSemtField = value
                Me.RaisePropertyChanged("pAliciSemt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property pAliciMahalle() As String
            Get
                Return Me.pAliciMahalleField
            End Get
            Set
                Me.pAliciMahalleField = value
                Me.RaisePropertyChanged("pAliciMahalle")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property pAliciMeydanBulvar() As String
            Get
                Return Me.pAliciMeydanBulvarField
            End Get
            Set
                Me.pAliciMeydanBulvarField = value
                Me.RaisePropertyChanged("pAliciMeydanBulvar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property pAliciCadde() As String
            Get
                Return Me.pAliciCaddeField
            End Get
            Set
                Me.pAliciCaddeField = value
                Me.RaisePropertyChanged("pAliciCadde")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property pAliciSokak() As String
            Get
                Return Me.pAliciSokakField
            End Get
            Set
                Me.pAliciSokakField = value
                Me.RaisePropertyChanged("pAliciSokak")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property pAliciTelIs() As String
            Get
                Return Me.pAliciTelIsField
            End Get
            Set
                Me.pAliciTelIsField = value
                Me.RaisePropertyChanged("pAliciTelIs")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property pAliciTelEv() As String
            Get
                Return Me.pAliciTelEvField
            End Get
            Set
                Me.pAliciTelEvField = value
                Me.RaisePropertyChanged("pAliciTelEv")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property pAliciTelCep() As String
            Get
                Return Me.pAliciTelCepField
            End Get
            Set
                Me.pAliciTelCepField = value
                Me.RaisePropertyChanged("pAliciTelCep")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property pAliciFax() As String
            Get
                Return Me.pAliciFaxField
            End Get
            Set
                Me.pAliciFaxField = value
                Me.RaisePropertyChanged("pAliciFax")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property pAliciEmail() As String
            Get
                Return Me.pAliciEmailField
            End Get
            Set
                Me.pAliciEmailField = value
                Me.RaisePropertyChanged("pAliciEmail")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property pAliciVergiDairesi() As String
            Get
                Return Me.pAliciVergiDairesiField
            End Get
            Set
                Me.pAliciVergiDairesiField = value
                Me.RaisePropertyChanged("pAliciVergiDairesi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property pAliciVergiNumarasi() As String
            Get
                Return Me.pAliciVergiNumarasiField
            End Get
            Set
                Me.pAliciVergiNumarasiField = value
                Me.RaisePropertyChanged("pAliciVergiNumarasi")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Gonderici
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pGonMusteriMngNoField As String
        
        Private pGonMusteriBayiNoField As String
        
        Private pGonMusteriSiparisNoField As String
        
        Private pGonMusteriAdiField As String
        
        Private pGonMusAdresFarkliField As String
        
        Private pGonIlAdiField As String
        
        Private pGonilceAdiField As String
        
        Private pGonAdresTextField As String
        
        Private pGonSemtField As String
        
        Private pGonMahalleField As String
        
        Private pGonMeydanBulvarField As String
        
        Private pGonCaddeField As String
        
        Private pGonSokakField As String
        
        Private pGonTelIsField As String
        
        Private pGonTelEvField As String
        
        Private pGonTelCepField As String
        
        Private pGonFaxField As String
        
        Private pGonEmailField As String
        
        Private pGonVergiDairesiField As String
        
        Private pGonVergiNumarasiField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property pGonMusteriMngNo() As String
            Get
                Return Me.pGonMusteriMngNoField
            End Get
            Set
                Me.pGonMusteriMngNoField = value
                Me.RaisePropertyChanged("pGonMusteriMngNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property pGonMusteriBayiNo() As String
            Get
                Return Me.pGonMusteriBayiNoField
            End Get
            Set
                Me.pGonMusteriBayiNoField = value
                Me.RaisePropertyChanged("pGonMusteriBayiNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property pGonMusteriSiparisNo() As String
            Get
                Return Me.pGonMusteriSiparisNoField
            End Get
            Set
                Me.pGonMusteriSiparisNoField = value
                Me.RaisePropertyChanged("pGonMusteriSiparisNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property pGonMusteriAdi() As String
            Get
                Return Me.pGonMusteriAdiField
            End Get
            Set
                Me.pGonMusteriAdiField = value
                Me.RaisePropertyChanged("pGonMusteriAdi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property pGonMusAdresFarkli() As String
            Get
                Return Me.pGonMusAdresFarkliField
            End Get
            Set
                Me.pGonMusAdresFarkliField = value
                Me.RaisePropertyChanged("pGonMusAdresFarkli")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property pGonIlAdi() As String
            Get
                Return Me.pGonIlAdiField
            End Get
            Set
                Me.pGonIlAdiField = value
                Me.RaisePropertyChanged("pGonIlAdi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property pGonilceAdi() As String
            Get
                Return Me.pGonilceAdiField
            End Get
            Set
                Me.pGonilceAdiField = value
                Me.RaisePropertyChanged("pGonilceAdi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property pGonAdresText() As String
            Get
                Return Me.pGonAdresTextField
            End Get
            Set
                Me.pGonAdresTextField = value
                Me.RaisePropertyChanged("pGonAdresText")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property pGonSemt() As String
            Get
                Return Me.pGonSemtField
            End Get
            Set
                Me.pGonSemtField = value
                Me.RaisePropertyChanged("pGonSemt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property pGonMahalle() As String
            Get
                Return Me.pGonMahalleField
            End Get
            Set
                Me.pGonMahalleField = value
                Me.RaisePropertyChanged("pGonMahalle")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property pGonMeydanBulvar() As String
            Get
                Return Me.pGonMeydanBulvarField
            End Get
            Set
                Me.pGonMeydanBulvarField = value
                Me.RaisePropertyChanged("pGonMeydanBulvar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property pGonCadde() As String
            Get
                Return Me.pGonCaddeField
            End Get
            Set
                Me.pGonCaddeField = value
                Me.RaisePropertyChanged("pGonCadde")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property pGonSokak() As String
            Get
                Return Me.pGonSokakField
            End Get
            Set
                Me.pGonSokakField = value
                Me.RaisePropertyChanged("pGonSokak")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property pGonTelIs() As String
            Get
                Return Me.pGonTelIsField
            End Get
            Set
                Me.pGonTelIsField = value
                Me.RaisePropertyChanged("pGonTelIs")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property pGonTelEv() As String
            Get
                Return Me.pGonTelEvField
            End Get
            Set
                Me.pGonTelEvField = value
                Me.RaisePropertyChanged("pGonTelEv")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property pGonTelCep() As String
            Get
                Return Me.pGonTelCepField
            End Get
            Set
                Me.pGonTelCepField = value
                Me.RaisePropertyChanged("pGonTelCep")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property pGonFax() As String
            Get
                Return Me.pGonFaxField
            End Get
            Set
                Me.pGonFaxField = value
                Me.RaisePropertyChanged("pGonFax")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property pGonEmail() As String
            Get
                Return Me.pGonEmailField
            End Get
            Set
                Me.pGonEmailField = value
                Me.RaisePropertyChanged("pGonEmail")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property pGonVergiDairesi() As String
            Get
                Return Me.pGonVergiDairesiField
            End Get
            Set
                Me.pGonVergiDairesiField = value
                Me.RaisePropertyChanged("pGonVergiDairesi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=19)>  _
        Public Property pGonVergiNumarasi() As String
            Get
                Return Me.pGonVergiNumarasiField
            End Get
            Set
                Me.pGonVergiNumarasiField = value
                Me.RaisePropertyChanged("pGonVergiNumarasi")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum OdemeSekli
        
        '''<remarks/>
        Gonderici_Odeyecek
        
        '''<remarks/>
        Alici_Odeyecek
        
        '''<remarks/>
        Platform_Odeyecek
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum TeslimSekli
        
        '''<remarks/>
        Adrese_Teslim
        
        '''<remarks/>
        Alici_Haberli
        
        '''<remarks/>
        Telefon_Ihbarli
        
        '''<remarks/>
        Mobil_Adrese_Teslim
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum KargoCinsi
        
        '''<remarks/>
        DOSYA
        
        '''<remarks/>
        MI
        
        '''<remarks/>
        PAKET
        
        '''<remarks/>
        KOLI
        
        '''<remarks/>
        SANDIK
        
        '''<remarks/>
        CUVAL
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum GondericiSms
        
        '''<remarks/>
        SmsGonderilsin
        
        '''<remarks/>
        SMSGonderilmesin
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum AliciSms
        
        '''<remarks/>
        SmsGonderilsin
        
        '''<remarks/>
        SMSGonderilmesin
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum KapidaOdeme
        
        '''<remarks/>
        Mal_Bedeli_Tahsil_Edilsin
        
        '''<remarks/>
        Mal_Bedeli_Tahsil_Edilmesin
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum AlimSekli
        
        '''<remarks/>
        AdrestenAlinacak
        
        '''<remarks/>
        SubeyeGetirilecek
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MusteriSiparisNewSoapChannel
        Inherits mngiade.MusteriSiparisNewSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MusteriSiparisNewSoapClient
        Inherits System.ServiceModel.ClientBase(Of mngiade.MusteriSiparisNewSoap)
        Implements mngiade.MusteriSiparisNewSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SiparisKayit_C2C( _
                    ByVal pKullaniciAdi As String,  _
                    ByVal pSifre As String,  _
                    ByVal pSiparisNo As String,  _
                    ByVal pBarkodText As String,  _
                    ByVal pIrsaliyeNo As String,  _
                    ByVal pUrunBedeli As String,  _
                    ByVal pGonderiParcaList() As mngiade.GonderiParca,  _
                    ByVal pGonderenMusteri As mngiade.Gonderici,  _
                    ByVal pAliciMusteri As mngiade.Alici,  _
                    ByVal pOdemeSekli As mngiade.OdemeSekli,  _
                    ByVal pTeslimSekli As mngiade.TeslimSekli,  _
                    ByVal pKargoCinsi As mngiade.KargoCinsi,  _
                    ByVal pGonSms As mngiade.GondericiSms,  _
                    ByVal pAliciSms As mngiade.AliciSms,  _
                    ByVal pKapidaTahsilat As mngiade.KapidaOdeme,  _
                    ByVal pAciklama As String) As String Implements mngiade.MusteriSiparisNewSoap.SiparisKayit_C2C
            Return MyBase.Channel.SiparisKayit_C2C(pKullaniciAdi, pSifre, pSiparisNo, pBarkodText, pIrsaliyeNo, pUrunBedeli, pGonderiParcaList, pGonderenMusteri, pAliciMusteri, pOdemeSekli, pTeslimSekli, pKargoCinsi, pGonSms, pAliciSms, pKapidaTahsilat, pAciklama)
        End Function
        
        Public Function SiparisKayit_C2CAsync( _
                    ByVal pKullaniciAdi As String,  _
                    ByVal pSifre As String,  _
                    ByVal pSiparisNo As String,  _
                    ByVal pBarkodText As String,  _
                    ByVal pIrsaliyeNo As String,  _
                    ByVal pUrunBedeli As String,  _
                    ByVal pGonderiParcaList() As mngiade.GonderiParca,  _
                    ByVal pGonderenMusteri As mngiade.Gonderici,  _
                    ByVal pAliciMusteri As mngiade.Alici,  _
                    ByVal pOdemeSekli As mngiade.OdemeSekli,  _
                    ByVal pTeslimSekli As mngiade.TeslimSekli,  _
                    ByVal pKargoCinsi As mngiade.KargoCinsi,  _
                    ByVal pGonSms As mngiade.GondericiSms,  _
                    ByVal pAliciSms As mngiade.AliciSms,  _
                    ByVal pKapidaTahsilat As mngiade.KapidaOdeme,  _
                    ByVal pAciklama As String) As System.Threading.Tasks.Task(Of String) Implements mngiade.MusteriSiparisNewSoap.SiparisKayit_C2CAsync
            Return MyBase.Channel.SiparisKayit_C2CAsync(pKullaniciAdi, pSifre, pSiparisNo, pBarkodText, pIrsaliyeNo, pUrunBedeli, pGonderiParcaList, pGonderenMusteri, pAliciMusteri, pOdemeSekli, pTeslimSekli, pKargoCinsi, pGonSms, pAliciSms, pKapidaTahsilat, pAciklama)
        End Function
        
        Public Function SiparisKayit_B2B(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pGondericiMngMusNo As String, ByVal pGondericiMusRefNo As String, ByVal pAliciMngMusNo As String, ByVal pAliciMusRefNo As String, ByVal pOtherParam() As String) As String Implements mngiade.MusteriSiparisNewSoap.SiparisKayit_B2B
            Return MyBase.Channel.SiparisKayit_B2B(pKullaniciAdi, pSifre, pSiparisNo, pGondericiMngMusNo, pGondericiMusRefNo, pAliciMngMusNo, pAliciMusRefNo, pOtherParam)
        End Function
        
        Public Function SiparisKayit_B2BAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pGondericiMngMusNo As String, ByVal pGondericiMusRefNo As String, ByVal pAliciMngMusNo As String, ByVal pAliciMusRefNo As String, ByVal pOtherParam() As String) As System.Threading.Tasks.Task(Of String) Implements mngiade.MusteriSiparisNewSoap.SiparisKayit_B2BAsync
            Return MyBase.Channel.SiparisKayit_B2BAsync(pKullaniciAdi, pSifre, pSiparisNo, pGondericiMngMusNo, pGondericiMusRefNo, pAliciMngMusNo, pAliciMusRefNo, pOtherParam)
        End Function
        
        Public Function SiparisIptali_C2C(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String) As String Implements mngiade.MusteriSiparisNewSoap.SiparisIptali_C2C
            Return MyBase.Channel.SiparisIptali_C2C(pKullaniciAdi, pSifre, pSiparisNo)
        End Function
        
        Public Function SiparisIptali_C2CAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String) As System.Threading.Tasks.Task(Of String) Implements mngiade.MusteriSiparisNewSoap.SiparisIptali_C2CAsync
            Return MyBase.Channel.SiparisIptali_C2CAsync(pKullaniciAdi, pSifre, pSiparisNo)
        End Function
        
        Public Function GelecekIadeSiparisKayit(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As String Implements mngiade.MusteriSiparisNewSoap.GelecekIadeSiparisKayit
            Return MyBase.Channel.GelecekIadeSiparisKayit(pKullaniciAdi, pSifre, pSiparisNo, pIrsaliyeNo, pGonderenMusteri, pOdemeSekli, pAciklama)
        End Function
        
        Public Function GelecekIadeSiparisKayitAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As System.Threading.Tasks.Task(Of String) Implements mngiade.MusteriSiparisNewSoap.GelecekIadeSiparisKayitAsync
            Return MyBase.Channel.GelecekIadeSiparisKayitAsync(pKullaniciAdi, pSifre, pSiparisNo, pIrsaliyeNo, pGonderenMusteri, pOdemeSekli, pAciklama)
        End Function
        
        Public Function GelecekGonderiKayit(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As String Implements mngiade.MusteriSiparisNewSoap.GelecekGonderiKayit
            Return MyBase.Channel.GelecekGonderiKayit(pKullaniciAdi, pSifre, pSiparisNo, pIrsaliyeNo, pGonderenMusteri, pOdemeSekli, pAciklama)
        End Function
        
        Public Function GelecekGonderiKayitAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As System.Threading.Tasks.Task(Of String) Implements mngiade.MusteriSiparisNewSoap.GelecekGonderiKayitAsync
            Return MyBase.Channel.GelecekGonderiKayitAsync(pKullaniciAdi, pSifre, pSiparisNo, pIrsaliyeNo, pGonderenMusteri, pOdemeSekli, pAciklama)
        End Function
        
        Public Function GelecekIadeSiparisIptali(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String) As String Implements mngiade.MusteriSiparisNewSoap.GelecekIadeSiparisIptali
            Return MyBase.Channel.GelecekIadeSiparisIptali(pKullaniciAdi, pSifre, pSiparisNo)
        End Function
        
        Public Function GelecekIadeSiparisIptaliAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String) As System.Threading.Tasks.Task(Of String) Implements mngiade.MusteriSiparisNewSoap.GelecekIadeSiparisIptaliAsync
            Return MyBase.Channel.GelecekIadeSiparisIptaliAsync(pKullaniciAdi, pSifre, pSiparisNo)
        End Function
        
        Public Function GelecekIadeSiparisKontrol(ByVal pRfSipGnMusteriNo As String, ByVal pRfSipGnMusteriSifre As String, ByVal pChBarkod As String, ByVal pChFaturaSeri As String, ByVal pChFaturaNo As String, ByVal pNmGonderiNo As String, ByVal pChSiparisNo As String, ByVal pGonderiCikisTarihi As String) As System.Data.DataSet Implements mngiade.MusteriSiparisNewSoap.GelecekIadeSiparisKontrol
            Return MyBase.Channel.GelecekIadeSiparisKontrol(pRfSipGnMusteriNo, pRfSipGnMusteriSifre, pChBarkod, pChFaturaSeri, pChFaturaNo, pNmGonderiNo, pChSiparisNo, pGonderiCikisTarihi)
        End Function
        
        Public Function GelecekIadeSiparisKontrolAsync(ByVal pRfSipGnMusteriNo As String, ByVal pRfSipGnMusteriSifre As String, ByVal pChBarkod As String, ByVal pChFaturaSeri As String, ByVal pChFaturaNo As String, ByVal pNmGonderiNo As String, ByVal pChSiparisNo As String, ByVal pGonderiCikisTarihi As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements mngiade.MusteriSiparisNewSoap.GelecekIadeSiparisKontrolAsync
            Return MyBase.Channel.GelecekIadeSiparisKontrolAsync(pRfSipGnMusteriNo, pRfSipGnMusteriSifre, pChBarkod, pChFaturaSeri, pChFaturaNo, pNmGonderiNo, pChSiparisNo, pGonderiCikisTarihi)
        End Function
        
        Public Function AdrestenAlimSiparisKayit(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pAlimsekli As mngiade.AlimSekli, ByVal pAlimIstekTarihi As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pAliciMusteri As mngiade.Alici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As String Implements mngiade.MusteriSiparisNewSoap.AdrestenAlimSiparisKayit
            Return MyBase.Channel.AdrestenAlimSiparisKayit(pKullaniciAdi, pSifre, pSiparisNo, pIrsaliyeNo, pAlimsekli, pAlimIstekTarihi, pGonderenMusteri, pAliciMusteri, pOdemeSekli, pAciklama)
        End Function
        
        Public Function AdrestenAlimSiparisKayitAsync(ByVal pKullaniciAdi As String, ByVal pSifre As String, ByVal pSiparisNo As String, ByVal pIrsaliyeNo As String, ByVal pAlimsekli As mngiade.AlimSekli, ByVal pAlimIstekTarihi As String, ByVal pGonderenMusteri As mngiade.Gonderici, ByVal pAliciMusteri As mngiade.Alici, ByVal pOdemeSekli As mngiade.OdemeSekli, ByVal pAciklama As String) As System.Threading.Tasks.Task(Of String) Implements mngiade.MusteriSiparisNewSoap.AdrestenAlimSiparisKayitAsync
            Return MyBase.Channel.AdrestenAlimSiparisKayitAsync(pKullaniciAdi, pSifre, pSiparisNo, pIrsaliyeNo, pAlimsekli, pAlimIstekTarihi, pGonderenMusteri, pAliciMusteri, pOdemeSekli, pAciklama)
        End Function
    End Class
End Namespace
