'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace eContPaymentreport
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ee.econt.com/services")>  _
    Partial Public Class [Error]
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private typeField As String
        
        Private messageField As String
        
        Private fieldsField() As String
        
        Private innerErrorsField() As [Error]
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
                Me.RaisePropertyChanged("type")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("fields", Order:=2)>  _
        Public Property fields() As String()
            Get
                Return Me.fieldsField
            End Get
            Set
                Me.fieldsField = value
                Me.RaisePropertyChanged("fields")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("innerErrors", Order:=3)>  _
        Public Property innerErrors() As [Error]()
            Get
                Return Me.innerErrorsField
            End Get
            Set
                Me.innerErrorsField = value
                Me.RaisePropertyChanged("innerErrors")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ee.econt.com/services/PaymentReport")>  _
    Partial Public Class PaymentReportRow
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private numField As Long
        
        Private typeField As String
        
        Private payTypeField As String
        
        Private payDateField As String
        
        Private amountField As Double
        
        Private currencyField As String
        
        Private createdTimeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property num() As Long
            Get
                Return Me.numField
            End Get
            Set
                Me.numField = value
                Me.RaisePropertyChanged("num")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
                Me.RaisePropertyChanged("type")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property payType() As String
            Get
                Return Me.payTypeField
            End Get
            Set
                Me.payTypeField = value
                Me.RaisePropertyChanged("payType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property payDate() As String
            Get
                Return Me.payDateField
            End Get
            Set
                Me.payDateField = value
                Me.RaisePropertyChanged("payDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property amount() As Double
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("amount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property currency() As String
            Get
                Return Me.currencyField
            End Get
            Set
                Me.currencyField = value
                Me.RaisePropertyChanged("currency")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property createdTime() As String
            Get
                Return Me.createdTimeField
            End Get
            Set
                Me.createdTimeField = value
                Me.RaisePropertyChanged("createdTime")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ee.econt.com/services/PaymentReport/R")>  _
    Partial Public Class PaymentReportRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dateToField As String
        
        Private dateFromField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dateTo() As String
            Get
                Return Me.dateToField
            End Get
            Set
                Me.dateToField = value
                Me.RaisePropertyChanged("dateTo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property dateFrom() As String
            Get
                Return Me.dateFromField
            End Get
            Set
                Me.dateFromField = value
                Me.RaisePropertyChanged("dateFrom")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ee.econt.com/services/PaymentReport", ConfigurationName:="eContPaymentreport.PaymentReportService")>  _
    Public Interface PaymentReportService
        
        'CODEGEN: Generating message contract since the operation PaymentReport is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="PaymentReport", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(eContPaymentreport.[Error]), Action:="PaymentReport", Name:="Error", [Namespace]:="http://ee.econt.com/services"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PaymentReport(ByVal request As eContPaymentreport.PaymentReportRequest1) As eContPaymentreport.PaymentReportResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="PaymentReport", ReplyAction:="*")>  _
        Function PaymentReportAsync(ByVal request As eContPaymentreport.PaymentReportRequest1) As System.Threading.Tasks.Task(Of eContPaymentreport.PaymentReportResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PaymentReportRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ee.econt.com/services/PaymentReport/R", Order:=0)>  _
        Public PaymentReportRequest As eContPaymentreport.PaymentReportRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PaymentReportRequest As eContPaymentreport.PaymentReportRequest)
            MyBase.New
            Me.PaymentReportRequest = PaymentReportRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PaymentReportResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ee.econt.com/services/PaymentReport", Order:=0)>  _
        Public PaymentReportRow As eContPaymentreport.PaymentReportRow
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PaymentReportRow As eContPaymentreport.PaymentReportRow)
            MyBase.New
            Me.PaymentReportRow = PaymentReportRow
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PaymentReportServiceChannel
        Inherits eContPaymentreport.PaymentReportService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PaymentReportServiceClient
        Inherits System.ServiceModel.ClientBase(Of eContPaymentreport.PaymentReportService)
        Implements eContPaymentreport.PaymentReportService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eContPaymentreport_PaymentReportService_PaymentReport(ByVal request As eContPaymentreport.PaymentReportRequest1) As eContPaymentreport.PaymentReportResponse Implements eContPaymentreport.PaymentReportService.PaymentReport
            Return MyBase.Channel.PaymentReport(request)
        End Function
        
        Public Function PaymentReport(ByVal PaymentReportRequest As eContPaymentreport.PaymentReportRequest) As eContPaymentreport.PaymentReportRow
            Dim inValue As eContPaymentreport.PaymentReportRequest1 = New eContPaymentreport.PaymentReportRequest1()
            inValue.PaymentReportRequest = PaymentReportRequest
            Dim retVal As eContPaymentreport.PaymentReportResponse = CType(Me,eContPaymentreport.PaymentReportService).PaymentReport(inValue)
            Return retVal.PaymentReportRow
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eContPaymentreport_PaymentReportService_PaymentReportAsync(ByVal request As eContPaymentreport.PaymentReportRequest1) As System.Threading.Tasks.Task(Of eContPaymentreport.PaymentReportResponse) Implements eContPaymentreport.PaymentReportService.PaymentReportAsync
            Return MyBase.Channel.PaymentReportAsync(request)
        End Function
        
        Public Function PaymentReportAsync(ByVal PaymentReportRequest As eContPaymentreport.PaymentReportRequest) As System.Threading.Tasks.Task(Of eContPaymentreport.PaymentReportResponse)
            Dim inValue As eContPaymentreport.PaymentReportRequest1 = New eContPaymentreport.PaymentReportRequest1()
            inValue.PaymentReportRequest = PaymentReportRequest
            Return CType(Me,eContPaymentreport.PaymentReportService).PaymentReportAsync(inValue)
        End Function
    End Class
End Namespace
