'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceRefAbit
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfFirma", [Namespace]:="http://tempuri.org/", ItemName:="firma"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfFirma
        Inherits System.Collections.Generic.List(Of WinTexDLL.ServiceRefAbit.firma)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfKalem", [Namespace]:="http://tempuri.org/", ItemName:="kalem"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfKalem
        Inherits System.Collections.Generic.List(Of WinTexDLL.ServiceRefAbit.kalem)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfTamamlayici", [Namespace]:="http://tempuri.org/", ItemName:="tamamlayici"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfTamamlayici
        Inherits System.Collections.Generic.List(Of WinTexDLL.ServiceRefAbit.tamamlayici)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfTcgbacmakapatma", [Namespace]:="http://tempuri.org/", ItemName:="tcgbacmakapatma"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfTcgbacmakapatma
        Inherits System.Collections.Generic.List(Of WinTexDLL.ServiceRefAbit.tcgbacmakapatma)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceRefAbit.AbitWsdlSoap")>  _
    Public Interface AbitWsdlSoap
        
        'CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AbitData", ReplyAction:="*")>  _
        Function AbitData(ByVal request As ServiceRefAbit.AbitDataRequest) As ServiceRefAbit.AbitDataResponse
        
        'CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetAllAbitData", ReplyAction:="*")>  _
        Function GetAllAbitData(ByVal request As ServiceRefAbit.GetAllAbitDataRequest) As ServiceRefAbit.GetAllAbitDataResponse
        
        'CODEGEN: Generating message contract since element name prmUser from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IhracatBeyanname", ReplyAction:="*")>  _
        Function IhracatBeyanname(ByVal request As ServiceRefAbit.IhracatBeyannameRequest) As ServiceRefAbit.IhracatBeyannameResponse
        
        'CODEGEN: Generating message contract since element name prmUser from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IntacGetir", ReplyAction:="*")>  _
        Function IntacGetir(ByVal request As ServiceRefAbit.IntacGetirRequest) As ServiceRefAbit.IntacGetirResponse
        
        'CODEGEN: Generating message contract since element name prmUser from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IntacGetirKalemBazinda", ReplyAction:="*")>  _
        Function IntacGetirKalemBazinda(ByVal request As ServiceRefAbit.IntacGetirKalemBazindaRequest) As ServiceRefAbit.IntacGetirKalemBazindaResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AbitDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AbitData", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.AbitDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.AbitDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AbitDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public user As WinTexDLL.ServiceRefAbit.Users
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal user As WinTexDLL.ServiceRefAbit.Users)
            MyBase.New
            Me.user = user
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AbitDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AbitDataResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.AbitDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.AbitDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AbitDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AbitDataResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfBeyanname
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AbitDataResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfBeyanname)
            MyBase.New
            Me.AbitDataResult = AbitDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAllAbitDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAllAbitData", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.GetAllAbitDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.GetAllAbitDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetAllAbitDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public user As WinTexDLL.ServiceRefAbit.PrmUserWithDate
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal user As WinTexDLL.ServiceRefAbit.PrmUserWithDate)
            MyBase.New
            Me.user = user
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAllAbitDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAllAbitDataResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.GetAllAbitDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.GetAllAbitDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetAllAbitDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetAllAbitDataResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfListBeyanname
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAllAbitDataResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfListBeyanname)
            MyBase.New
            Me.GetAllAbitDataResult = GetAllAbitDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IhracatBeyannameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IhracatBeyanname", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.IhracatBeyannameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.IhracatBeyannameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class IhracatBeyannameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public prmUser As WinTexDLL.ServiceRefAbit.PrmUserIhracatBeyanname
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal prmUser As WinTexDLL.ServiceRefAbit.PrmUserIhracatBeyanname)
            MyBase.New
            Me.prmUser = prmUser
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IhracatBeyannameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IhracatBeyannameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.IhracatBeyannameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.IhracatBeyannameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class IhracatBeyannameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public IhracatBeyannameResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfGelen
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IhracatBeyannameResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfGelen)
            MyBase.New
            Me.IhracatBeyannameResult = IhracatBeyannameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IntacGetirRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IntacGetir", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.IntacGetirRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.IntacGetirRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class IntacGetirRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public prmUser As WinTexDLL.ServiceRefAbit.PrmUserIntacGetir
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal prmUser As WinTexDLL.ServiceRefAbit.PrmUserIntacGetir)
            MyBase.New
            Me.prmUser = prmUser
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IntacGetirResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IntacGetirResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.IntacGetirResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.IntacGetirResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class IntacGetirResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public IntacGetirResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfIntacBilgisi
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IntacGetirResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfIntacBilgisi)
            MyBase.New
            Me.IntacGetirResult = IntacGetirResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IntacGetirKalemBazindaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IntacGetirKalemBazinda", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.IntacGetirKalemBazindaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.IntacGetirKalemBazindaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class IntacGetirKalemBazindaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public prmUser As WinTexDLL.ServiceRefAbit.PrmUserIntacKalemBazindaGetir
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal prmUser As WinTexDLL.ServiceRefAbit.PrmUserIntacKalemBazindaGetir)
            MyBase.New
            Me.prmUser = prmUser
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IntacGetirKalemBazindaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IntacGetirKalemBazindaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceRefAbit.IntacGetirKalemBazindaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceRefAbit.IntacGetirKalemBazindaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class IntacGetirKalemBazindaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public IntacGetirKalemBazindaResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfIntacBilgisiKalemBazinda
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IntacGetirKalemBazindaResult As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfIntacBilgisiKalemBazinda)
            MyBase.New
            Me.IntacGetirKalemBazindaResult = IntacGetirKalemBazindaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface AbitWsdlSoapChannel
        Inherits ServiceRefAbit.AbitWsdlSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AbitWsdlSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceRefAbit.AbitWsdlSoap)
        Implements ServiceRefAbit.AbitWsdlSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceRefAbit_AbitWsdlSoap_AbitData(ByVal request As ServiceRefAbit.AbitDataRequest) As ServiceRefAbit.AbitDataResponse Implements ServiceRefAbit.AbitWsdlSoap.AbitData
            Return MyBase.Channel.AbitData(request)
        End Function
        
        Public Function AbitData(ByVal user As WinTexDLL.ServiceRefAbit.Users) As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfBeyanname
            Dim inValue As ServiceRefAbit.AbitDataRequest = New ServiceRefAbit.AbitDataRequest()
            inValue.Body = New ServiceRefAbit.AbitDataRequestBody()
            inValue.Body.user = user
            Dim retVal As ServiceRefAbit.AbitDataResponse = CType(Me,ServiceRefAbit.AbitWsdlSoap).AbitData(inValue)
            Return retVal.Body.AbitDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceRefAbit_AbitWsdlSoap_GetAllAbitData(ByVal request As ServiceRefAbit.GetAllAbitDataRequest) As ServiceRefAbit.GetAllAbitDataResponse Implements ServiceRefAbit.AbitWsdlSoap.GetAllAbitData
            Return MyBase.Channel.GetAllAbitData(request)
        End Function
        
        Public Function GetAllAbitData(ByVal user As WinTexDLL.ServiceRefAbit.PrmUserWithDate) As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfListBeyanname
            Dim inValue As ServiceRefAbit.GetAllAbitDataRequest = New ServiceRefAbit.GetAllAbitDataRequest()
            inValue.Body = New ServiceRefAbit.GetAllAbitDataRequestBody()
            inValue.Body.user = user
            Dim retVal As ServiceRefAbit.GetAllAbitDataResponse = CType(Me,ServiceRefAbit.AbitWsdlSoap).GetAllAbitData(inValue)
            Return retVal.Body.GetAllAbitDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceRefAbit_AbitWsdlSoap_IhracatBeyanname(ByVal request As ServiceRefAbit.IhracatBeyannameRequest) As ServiceRefAbit.IhracatBeyannameResponse Implements ServiceRefAbit.AbitWsdlSoap.IhracatBeyanname
            Return MyBase.Channel.IhracatBeyanname(request)
        End Function
        
        Public Function IhracatBeyanname(ByVal prmUser As WinTexDLL.ServiceRefAbit.PrmUserIhracatBeyanname) As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfGelen
            Dim inValue As ServiceRefAbit.IhracatBeyannameRequest = New ServiceRefAbit.IhracatBeyannameRequest()
            inValue.Body = New ServiceRefAbit.IhracatBeyannameRequestBody()
            inValue.Body.prmUser = prmUser
            Dim retVal As ServiceRefAbit.IhracatBeyannameResponse = CType(Me,ServiceRefAbit.AbitWsdlSoap).IhracatBeyanname(inValue)
            Return retVal.Body.IhracatBeyannameResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceRefAbit_AbitWsdlSoap_IntacGetir(ByVal request As ServiceRefAbit.IntacGetirRequest) As ServiceRefAbit.IntacGetirResponse Implements ServiceRefAbit.AbitWsdlSoap.IntacGetir
            Return MyBase.Channel.IntacGetir(request)
        End Function
        
        Public Function IntacGetir(ByVal prmUser As WinTexDLL.ServiceRefAbit.PrmUserIntacGetir) As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfIntacBilgisi
            Dim inValue As ServiceRefAbit.IntacGetirRequest = New ServiceRefAbit.IntacGetirRequest()
            inValue.Body = New ServiceRefAbit.IntacGetirRequestBody()
            inValue.Body.prmUser = prmUser
            Dim retVal As ServiceRefAbit.IntacGetirResponse = CType(Me,ServiceRefAbit.AbitWsdlSoap).IntacGetir(inValue)
            Return retVal.Body.IntacGetirResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceRefAbit_AbitWsdlSoap_IntacGetirKalemBazinda(ByVal request As ServiceRefAbit.IntacGetirKalemBazindaRequest) As ServiceRefAbit.IntacGetirKalemBazindaResponse Implements ServiceRefAbit.AbitWsdlSoap.IntacGetirKalemBazinda
            Return MyBase.Channel.IntacGetirKalemBazinda(request)
        End Function
        
        Public Function IntacGetirKalemBazinda(ByVal prmUser As WinTexDLL.ServiceRefAbit.PrmUserIntacKalemBazindaGetir) As WinTexDLL.ServiceRefAbit.WebServisResultTypeOfIntacBilgisiKalemBazinda
            Dim inValue As ServiceRefAbit.IntacGetirKalemBazindaRequest = New ServiceRefAbit.IntacGetirKalemBazindaRequest()
            inValue.Body = New ServiceRefAbit.IntacGetirKalemBazindaRequestBody()
            inValue.Body.prmUser = prmUser
            Dim retVal As ServiceRefAbit.IntacGetirKalemBazindaResponse = CType(Me,ServiceRefAbit.AbitWsdlSoap).IntacGetirKalemBazinda(inValue)
            Return retVal.Body.IntacGetirKalemBazindaResult
        End Function
    End Class
End Namespace
