'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace tr.com.araskargo.customerservicestest
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpsBinding_IArasCargoIntegrationService", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ArasCargoIntegrationService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetQueryDSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetQueryXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetQueryJSONOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetDataXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallCourierOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WinTexMNG.My.MySettings.Default.WinTexMNG_tr_com_araskargo_customerservicestest_ArasCargoIntegrationService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetQueryDSCompleted As GetQueryDSCompletedEventHandler
        
        '''<remarks/>
        Public Event GetQueryXMLCompleted As GetQueryXMLCompletedEventHandler
        
        '''<remarks/>
        Public Event GetQueryJSONCompleted As GetQueryJSONCompletedEventHandler
        
        '''<remarks/>
        Public Event SetDataXMLCompleted As SetDataXMLCompletedEventHandler
        
        '''<remarks/>
        Public Event CallCourierCompleted As CallCourierCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IArasCargoIntegrationService/GetQueryDS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetQueryDS(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal loginInfo As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal queryInfo As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetQueryDS", New Object() {loginInfo, queryInfo})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetQueryDSAsync(ByVal loginInfo As String, ByVal queryInfo As String)
            Me.GetQueryDSAsync(loginInfo, queryInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetQueryDSAsync(ByVal loginInfo As String, ByVal queryInfo As String, ByVal userState As Object)
            If (Me.GetQueryDSOperationCompleted Is Nothing) Then
                Me.GetQueryDSOperationCompleted = AddressOf Me.OnGetQueryDSOperationCompleted
            End If
            Me.InvokeAsync("GetQueryDS", New Object() {loginInfo, queryInfo}, Me.GetQueryDSOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetQueryDSOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetQueryDSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetQueryDSCompleted(Me, New GetQueryDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IArasCargoIntegrationService/GetQueryXML", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetQueryXML(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal loginInfo As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal queryInfo As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GetQueryXML", New Object() {loginInfo, queryInfo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetQueryXMLAsync(ByVal loginInfo As String, ByVal queryInfo As String)
            Me.GetQueryXMLAsync(loginInfo, queryInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetQueryXMLAsync(ByVal loginInfo As String, ByVal queryInfo As String, ByVal userState As Object)
            If (Me.GetQueryXMLOperationCompleted Is Nothing) Then
                Me.GetQueryXMLOperationCompleted = AddressOf Me.OnGetQueryXMLOperationCompleted
            End If
            Me.InvokeAsync("GetQueryXML", New Object() {loginInfo, queryInfo}, Me.GetQueryXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetQueryXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetQueryXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetQueryXMLCompleted(Me, New GetQueryXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IArasCargoIntegrationService/GetQueryJSON", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetQueryJSON(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal loginInfo As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal queryInfo As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GetQueryJSON", New Object() {loginInfo, queryInfo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetQueryJSONAsync(ByVal loginInfo As String, ByVal queryInfo As String)
            Me.GetQueryJSONAsync(loginInfo, queryInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetQueryJSONAsync(ByVal loginInfo As String, ByVal queryInfo As String, ByVal userState As Object)
            If (Me.GetQueryJSONOperationCompleted Is Nothing) Then
                Me.GetQueryJSONOperationCompleted = AddressOf Me.OnGetQueryJSONOperationCompleted
            End If
            Me.InvokeAsync("GetQueryJSON", New Object() {loginInfo, queryInfo}, Me.GetQueryJSONOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetQueryJSONOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetQueryJSONCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetQueryJSONCompleted(Me, New GetQueryJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IArasCargoIntegrationService/SetDataXML", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SetDataXML(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal loginInfo As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal queryInfo As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("SetDataXML", New Object() {loginInfo, queryInfo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SetDataXMLAsync(ByVal loginInfo As String, ByVal queryInfo As String)
            Me.SetDataXMLAsync(loginInfo, queryInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetDataXMLAsync(ByVal loginInfo As String, ByVal queryInfo As String, ByVal userState As Object)
            If (Me.SetDataXMLOperationCompleted Is Nothing) Then
                Me.SetDataXMLOperationCompleted = AddressOf Me.OnSetDataXMLOperationCompleted
            End If
            Me.InvokeAsync("SetDataXML", New Object() {loginInfo, queryInfo}, Me.SetDataXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetDataXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetDataXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetDataXMLCompleted(Me, New SetDataXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IArasCargoIntegrationService/CallCourier", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallCourier(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal loginInfo As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal queryInfo As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> CallCourierReturn
            Dim results() As Object = Me.Invoke("CallCourier", New Object() {loginInfo, queryInfo})
            Return CType(results(0),CallCourierReturn)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallCourierAsync(ByVal loginInfo As String, ByVal queryInfo As String)
            Me.CallCourierAsync(loginInfo, queryInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallCourierAsync(ByVal loginInfo As String, ByVal queryInfo As String, ByVal userState As Object)
            If (Me.CallCourierOperationCompleted Is Nothing) Then
                Me.CallCourierOperationCompleted = AddressOf Me.OnCallCourierOperationCompleted
            End If
            Me.InvokeAsync("CallCourier", New Object() {loginInfo, queryInfo}, Me.CallCourierOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallCourierOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallCourierCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallCourierCompleted(Me, New CallCourierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/CustCargoInfo.Models")>  _
    Partial Public Class CallCourierReturn
        
        Private countField As Integer
        
        Private countFieldSpecified As Boolean
        
        Private resultField As Integer
        
        Private resultFieldSpecified As Boolean
        
        Private resultMessageField As String
        
        '''<remarks/>
        Public Property count() As Integer
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property countSpecified() As Boolean
            Get
                Return Me.countFieldSpecified
            End Get
            Set
                Me.countFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property result() As Integer
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property resultSpecified() As Boolean
            Get
                Return Me.resultFieldSpecified
            End Get
            Set
                Me.resultFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property resultMessage() As String
            Get
                Return Me.resultMessageField
            End Get
            Set
                Me.resultMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetQueryDSCompletedEventHandler(ByVal sender As Object, ByVal e As GetQueryDSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetQueryDSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetQueryXMLCompletedEventHandler(ByVal sender As Object, ByVal e As GetQueryXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetQueryXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetQueryJSONCompletedEventHandler(ByVal sender As Object, ByVal e As GetQueryJSONCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetQueryJSONCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub SetDataXMLCompletedEventHandler(ByVal sender As Object, ByVal e As SetDataXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetDataXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub CallCourierCompletedEventHandler(ByVal sender As Object, ByVal e As CallCourierCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallCourierCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CallCourierReturn
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CallCourierReturn)
            End Get
        End Property
    End Class
End Namespace
