'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace eContThreeWayLogistics
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ee.econt.com/services")>  _
    Partial Public Class [Error]
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private typeField As String
        
        Private messageField As String
        
        Private fieldsField() As String
        
        Private innerErrorsField() As [Error]
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
                Me.RaisePropertyChanged("type")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("fields", Order:=2)>  _
        Public Property fields() As String()
            Get
                Return Me.fieldsField
            End Get
            Set
                Me.fieldsField = value
                Me.RaisePropertyChanged("fields")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("innerErrors", Order:=3)>  _
        Public Property innerErrors() As [Error]()
            Get
                Return Me.innerErrorsField
            End Get
            Set
                Me.innerErrorsField = value
                Me.RaisePropertyChanged("innerErrors")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ee.econt.com/services/ThreeWayLogistics/R")>  _
    Partial Public Class ThreeWayLogisticsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ee.econt.com/services/ThreeWayLogistics/R")>  _
    Partial Public Class ThreeWayLogisticsRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private requester_nameField As String
        
        Private requester_phoneField As String
        
        Private requester_emailField As String
        
        Private requester_company_nameField As String
        
        Private requester_usernameField As String
        
        Private supplier_company_nameField As String
        
        Private supplier_contact_personField As String
        
        Private supplier_phoneField As String
        
        Private supplier_cityField As String
        
        Private supplier_addressField As String
        
        Private supplier_date_for_visitField As String
        
        Private supplier_time_for_visitField As String
        
        Private receiver_nameField As String
        
        Private receiver_company_nameField As String
        
        Private receiver_phoneField As String
        
        Private receiver_emailField As String
        
        Private description_shipment_descriptionField As String
        
        Private description_shipment_countField As String
        
        Private description_shipment_weightField As String
        
        Private description_additional_instructionsField As String
        
        Private description_payment_sum_to_supplierField As String
        
        Private delivery_details_cityField As String
        
        Private delivery_details_addressField As String
        
        Private delivery_details_officeField As String
        
        Private dcField As String
        
        Private dccpField As String
        
        Private email_on_deliveryField As String
        
        Private invoice_before_payField As String
        
        Private previewField As String
        
        Private testField As String
        
        Private payment_delivery_and_return_by_meField As String
        
        Private payment_return_by_meField As String
        
        Private payment_delivery_by_requesterField As String
        
        Private payment_delivery_by_receiverField As String
        
        Private oc_sumField As String
        
        Private cd_sumField As String
        
        Private priority_delivery_time_beforeField As String
        
        Private priority_delivery_time_afterField As String
        
        Private priority_delivery_time_inField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property requester_name() As String
            Get
                Return Me.requester_nameField
            End Get
            Set
                Me.requester_nameField = value
                Me.RaisePropertyChanged("requester_name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property requester_phone() As String
            Get
                Return Me.requester_phoneField
            End Get
            Set
                Me.requester_phoneField = value
                Me.RaisePropertyChanged("requester_phone")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property requester_email() As String
            Get
                Return Me.requester_emailField
            End Get
            Set
                Me.requester_emailField = value
                Me.RaisePropertyChanged("requester_email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property requester_company_name() As String
            Get
                Return Me.requester_company_nameField
            End Get
            Set
                Me.requester_company_nameField = value
                Me.RaisePropertyChanged("requester_company_name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property requester_username() As String
            Get
                Return Me.requester_usernameField
            End Get
            Set
                Me.requester_usernameField = value
                Me.RaisePropertyChanged("requester_username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property supplier_company_name() As String
            Get
                Return Me.supplier_company_nameField
            End Get
            Set
                Me.supplier_company_nameField = value
                Me.RaisePropertyChanged("supplier_company_name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property supplier_contact_person() As String
            Get
                Return Me.supplier_contact_personField
            End Get
            Set
                Me.supplier_contact_personField = value
                Me.RaisePropertyChanged("supplier_contact_person")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property supplier_phone() As String
            Get
                Return Me.supplier_phoneField
            End Get
            Set
                Me.supplier_phoneField = value
                Me.RaisePropertyChanged("supplier_phone")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property supplier_city() As String
            Get
                Return Me.supplier_cityField
            End Get
            Set
                Me.supplier_cityField = value
                Me.RaisePropertyChanged("supplier_city")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property supplier_address() As String
            Get
                Return Me.supplier_addressField
            End Get
            Set
                Me.supplier_addressField = value
                Me.RaisePropertyChanged("supplier_address")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property supplier_date_for_visit() As String
            Get
                Return Me.supplier_date_for_visitField
            End Get
            Set
                Me.supplier_date_for_visitField = value
                Me.RaisePropertyChanged("supplier_date_for_visit")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property supplier_time_for_visit() As String
            Get
                Return Me.supplier_time_for_visitField
            End Get
            Set
                Me.supplier_time_for_visitField = value
                Me.RaisePropertyChanged("supplier_time_for_visit")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property receiver_name() As String
            Get
                Return Me.receiver_nameField
            End Get
            Set
                Me.receiver_nameField = value
                Me.RaisePropertyChanged("receiver_name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property receiver_company_name() As String
            Get
                Return Me.receiver_company_nameField
            End Get
            Set
                Me.receiver_company_nameField = value
                Me.RaisePropertyChanged("receiver_company_name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property receiver_phone() As String
            Get
                Return Me.receiver_phoneField
            End Get
            Set
                Me.receiver_phoneField = value
                Me.RaisePropertyChanged("receiver_phone")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property receiver_email() As String
            Get
                Return Me.receiver_emailField
            End Get
            Set
                Me.receiver_emailField = value
                Me.RaisePropertyChanged("receiver_email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property description_shipment_description() As String
            Get
                Return Me.description_shipment_descriptionField
            End Get
            Set
                Me.description_shipment_descriptionField = value
                Me.RaisePropertyChanged("description_shipment_description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property description_shipment_count() As String
            Get
                Return Me.description_shipment_countField
            End Get
            Set
                Me.description_shipment_countField = value
                Me.RaisePropertyChanged("description_shipment_count")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property description_shipment_weight() As String
            Get
                Return Me.description_shipment_weightField
            End Get
            Set
                Me.description_shipment_weightField = value
                Me.RaisePropertyChanged("description_shipment_weight")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=19)>  _
        Public Property description_additional_instructions() As String
            Get
                Return Me.description_additional_instructionsField
            End Get
            Set
                Me.description_additional_instructionsField = value
                Me.RaisePropertyChanged("description_additional_instructions")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=20)>  _
        Public Property description_payment_sum_to_supplier() As String
            Get
                Return Me.description_payment_sum_to_supplierField
            End Get
            Set
                Me.description_payment_sum_to_supplierField = value
                Me.RaisePropertyChanged("description_payment_sum_to_supplier")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=21)>  _
        Public Property delivery_details_city() As String
            Get
                Return Me.delivery_details_cityField
            End Get
            Set
                Me.delivery_details_cityField = value
                Me.RaisePropertyChanged("delivery_details_city")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=22)>  _
        Public Property delivery_details_address() As String
            Get
                Return Me.delivery_details_addressField
            End Get
            Set
                Me.delivery_details_addressField = value
                Me.RaisePropertyChanged("delivery_details_address")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=23)>  _
        Public Property delivery_details_office() As String
            Get
                Return Me.delivery_details_officeField
            End Get
            Set
                Me.delivery_details_officeField = value
                Me.RaisePropertyChanged("delivery_details_office")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=24)>  _
        Public Property dc() As String
            Get
                Return Me.dcField
            End Get
            Set
                Me.dcField = value
                Me.RaisePropertyChanged("dc")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=25)>  _
        Public Property dccp() As String
            Get
                Return Me.dccpField
            End Get
            Set
                Me.dccpField = value
                Me.RaisePropertyChanged("dccp")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=26)>  _
        Public Property email_on_delivery() As String
            Get
                Return Me.email_on_deliveryField
            End Get
            Set
                Me.email_on_deliveryField = value
                Me.RaisePropertyChanged("email_on_delivery")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=27)>  _
        Public Property invoice_before_pay() As String
            Get
                Return Me.invoice_before_payField
            End Get
            Set
                Me.invoice_before_payField = value
                Me.RaisePropertyChanged("invoice_before_pay")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=28)>  _
        Public Property preview() As String
            Get
                Return Me.previewField
            End Get
            Set
                Me.previewField = value
                Me.RaisePropertyChanged("preview")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=29)>  _
        Public Property test() As String
            Get
                Return Me.testField
            End Get
            Set
                Me.testField = value
                Me.RaisePropertyChanged("test")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=30)>  _
        Public Property payment_delivery_and_return_by_me() As String
            Get
                Return Me.payment_delivery_and_return_by_meField
            End Get
            Set
                Me.payment_delivery_and_return_by_meField = value
                Me.RaisePropertyChanged("payment_delivery_and_return_by_me")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=31)>  _
        Public Property payment_return_by_me() As String
            Get
                Return Me.payment_return_by_meField
            End Get
            Set
                Me.payment_return_by_meField = value
                Me.RaisePropertyChanged("payment_return_by_me")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=32)>  _
        Public Property payment_delivery_by_requester() As String
            Get
                Return Me.payment_delivery_by_requesterField
            End Get
            Set
                Me.payment_delivery_by_requesterField = value
                Me.RaisePropertyChanged("payment_delivery_by_requester")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=33)>  _
        Public Property payment_delivery_by_receiver() As String
            Get
                Return Me.payment_delivery_by_receiverField
            End Get
            Set
                Me.payment_delivery_by_receiverField = value
                Me.RaisePropertyChanged("payment_delivery_by_receiver")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=34)>  _
        Public Property oc_sum() As String
            Get
                Return Me.oc_sumField
            End Get
            Set
                Me.oc_sumField = value
                Me.RaisePropertyChanged("oc_sum")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=35)>  _
        Public Property cd_sum() As String
            Get
                Return Me.cd_sumField
            End Get
            Set
                Me.cd_sumField = value
                Me.RaisePropertyChanged("cd_sum")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=36)>  _
        Public Property priority_delivery_time_before() As String
            Get
                Return Me.priority_delivery_time_beforeField
            End Get
            Set
                Me.priority_delivery_time_beforeField = value
                Me.RaisePropertyChanged("priority_delivery_time_before")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=37)>  _
        Public Property priority_delivery_time_after() As String
            Get
                Return Me.priority_delivery_time_afterField
            End Get
            Set
                Me.priority_delivery_time_afterField = value
                Me.RaisePropertyChanged("priority_delivery_time_after")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=38)>  _
        Public Property priority_delivery_time_in() As String
            Get
                Return Me.priority_delivery_time_inField
            End Get
            Set
                Me.priority_delivery_time_inField = value
                Me.RaisePropertyChanged("priority_delivery_time_in")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ee.econt.com/services/ThreeWayLogistics", ConfigurationName:="eContThreeWayLogistics.ThreeWayLogisticsService")>  _
    Public Interface ThreeWayLogisticsService
        
        'CODEGEN: Generating message contract since the operation threeWayLogistics is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="threeWayLogistics", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(eContThreeWayLogistics.[Error]), Action:="threeWayLogistics", Name:="Error", [Namespace]:="http://ee.econt.com/services"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function threeWayLogistics(ByVal request As eContThreeWayLogistics.threeWayLogisticsRequest1) As eContThreeWayLogistics.threeWayLogisticsResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="threeWayLogistics", ReplyAction:="*")>  _
        Function threeWayLogisticsAsync(ByVal request As eContThreeWayLogistics.threeWayLogisticsRequest1) As System.Threading.Tasks.Task(Of eContThreeWayLogistics.threeWayLogisticsResponse1)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class threeWayLogisticsRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ee.econt.com/services/ThreeWayLogistics/R", Order:=0)>  _
        Public ThreeWayLogisticsRequest As eContThreeWayLogistics.ThreeWayLogisticsRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ThreeWayLogisticsRequest As eContThreeWayLogistics.ThreeWayLogisticsRequest)
            MyBase.New
            Me.ThreeWayLogisticsRequest = ThreeWayLogisticsRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class threeWayLogisticsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ee.econt.com/services/ThreeWayLogistics/R", Order:=0)>  _
        Public ThreeWayLogisticsResponse As eContThreeWayLogistics.ThreeWayLogisticsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ThreeWayLogisticsResponse As eContThreeWayLogistics.ThreeWayLogisticsResponse)
            MyBase.New
            Me.ThreeWayLogisticsResponse = ThreeWayLogisticsResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ThreeWayLogisticsServiceChannel
        Inherits eContThreeWayLogistics.ThreeWayLogisticsService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ThreeWayLogisticsServiceClient
        Inherits System.ServiceModel.ClientBase(Of eContThreeWayLogistics.ThreeWayLogisticsService)
        Implements eContThreeWayLogistics.ThreeWayLogisticsService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eContThreeWayLogistics_ThreeWayLogisticsService_threeWayLogistics(ByVal request As eContThreeWayLogistics.threeWayLogisticsRequest1) As eContThreeWayLogistics.threeWayLogisticsResponse1 Implements eContThreeWayLogistics.ThreeWayLogisticsService.threeWayLogistics
            Return MyBase.Channel.threeWayLogistics(request)
        End Function
        
        Public Function threeWayLogistics(ByVal ThreeWayLogisticsRequest As eContThreeWayLogistics.ThreeWayLogisticsRequest) As eContThreeWayLogistics.ThreeWayLogisticsResponse
            Dim inValue As eContThreeWayLogistics.threeWayLogisticsRequest1 = New eContThreeWayLogistics.threeWayLogisticsRequest1()
            inValue.ThreeWayLogisticsRequest = ThreeWayLogisticsRequest
            Dim retVal As eContThreeWayLogistics.threeWayLogisticsResponse1 = CType(Me,eContThreeWayLogistics.ThreeWayLogisticsService).threeWayLogistics(inValue)
            Return retVal.ThreeWayLogisticsResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eContThreeWayLogistics_ThreeWayLogisticsService_threeWayLogisticsAsync(ByVal request As eContThreeWayLogistics.threeWayLogisticsRequest1) As System.Threading.Tasks.Task(Of eContThreeWayLogistics.threeWayLogisticsResponse1) Implements eContThreeWayLogistics.ThreeWayLogisticsService.threeWayLogisticsAsync
            Return MyBase.Channel.threeWayLogisticsAsync(request)
        End Function
        
        Public Function threeWayLogisticsAsync(ByVal ThreeWayLogisticsRequest As eContThreeWayLogistics.ThreeWayLogisticsRequest) As System.Threading.Tasks.Task(Of eContThreeWayLogistics.threeWayLogisticsResponse1)
            Dim inValue As eContThreeWayLogistics.threeWayLogisticsRequest1 = New eContThreeWayLogistics.threeWayLogisticsRequest1()
            inValue.ThreeWayLogisticsRequest = ThreeWayLogisticsRequest
            Return CType(Me,eContThreeWayLogistics.ThreeWayLogisticsService).threeWayLogisticsAsync(inValue)
        End Function
    End Class
End Namespace
