'----------------------
' <auto-generated>
'     Generated using the NSwag toolchain v12.0.5.0 (NJsonSchema v9.13.2.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
' </auto-generated>
'----------------------

Namespace Ykk.WebApi.ClientConsole
#Disable Warning ' Disable all warnings

    <System.CodeDom.Compiler.GeneratedCode("NSwag", "12.0.5.0 (NJsonSchema v9.13.2.0 (Newtonsoft.Json v11.0.0.0))")>
    Partial Public Class Client
        Private _baseUrl As String = String.Empty
        Private _settings As System.Lazy(Of Newtonsoft.Json.JsonSerializerSettings)

        Public Sub New(ByVal baseUrl As String)
            Me.BaseUrl = baseUrl
            _settings = New System.Lazy(Of Newtonsoft.Json.JsonSerializerSettings)(Function()
                                                                                       Dim settings = New Newtonsoft.Json.JsonSerializerSettings()
                                                                                       UpdateJsonSerializerSettings(settings)
                                                                                       Return settings
                                                                                   End Function)
        End Sub

        Public Property BaseUrl() As String
            Get
                Return _baseUrl
            End Get
            Set(ByVal value As String)
                _baseUrl = value
            End Set
        End Property

        Protected ReadOnly Property JsonSerializerSettings() As Newtonsoft.Json.JsonSerializerSettings
            Get
                Return _settings.Value
            End Get
        End Property

        Partial Private Sub UpdateJsonSerializerSettings(ByVal settings As Newtonsoft.Json.JsonSerializerSettings)
        End Sub
        Partial Private Sub PrepareRequest(ByVal client As System.Net.Http.HttpClient, ByVal request As System.Net.Http.HttpRequestMessage, ByVal url As String)
        End Sub
        Partial Private Sub PrepareRequest(ByVal client As System.Net.Http.HttpClient, ByVal request As System.Net.Http.HttpRequestMessage, ByVal urlBuilder As System.Text.StringBuilder)
        End Sub
        Partial Private Sub ProcessResponse(ByVal client As System.Net.Http.HttpClient, ByVal response As System.Net.Http.HttpResponseMessage)
        End Sub

        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        Public Function LoginAsync(ByVal model As LoginModel) As System.Threading.Tasks.Task(Of String)
            Return LoginAsync(model, System.Threading.CancellationToken.None)
        End Function

        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        ''' <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        Public Async Function LoginAsync(ByVal model As LoginModel, ByVal cancellationToken As System.Threading.CancellationToken) As System.Threading.Tasks.Task(Of String)
            Dim urlBuilder_ = New System.Text.StringBuilder()
            urlBuilder_.Append(If(BaseUrl IsNot Nothing, BaseUrl.TrimEnd("/"c), String.Empty)).Append("/Authentication/Login")

            Dim client_ = New System.Net.Http.HttpClient()
            Try
                Using request_ = New System.Net.Http.HttpRequestMessage()
                    Dim content_ = New System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(model, _settings.Value))
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json")
                    request_.Content = content_
                    request_.Method = New System.Net.Http.HttpMethod("POST")
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"))

                    PrepareRequest(client_, request_, urlBuilder_)
                    Dim url_ = urlBuilder_.ToString()
                    request_.RequestUri = New System.Uri(url_, System.UriKind.RelativeOrAbsolute)
                    PrepareRequest(client_, request_, url_)

                    Dim response_ = Await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(False)
                    Try
                        Dim headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, Function(h_) h_.Key, Function(h_) h_.Value)
                        If response_.Content IsNot Nothing AndAlso response_.Content.Headers IsNot Nothing Then
                            For Each item_ İn response_.Content.Headers
                                headers_(item_.Key) = item_.Value
                            Next item_
                        End If

                        ProcessResponse(client_, response_)

                        Dim status_ = CInt(Math.Truncate(response_.StatusCode)).ToString()
                        If status_ = "200" Then
                            Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                            Dim result_ = Nothing
                            Try
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of String)(responseData_, _settings.Value)
                                Return result_
                            Catch exception_ As System.Exception
                                Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                            End Try
                        Else
                            If status_ = "400" Then
                                Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                Dim result_ = Nothing
                                Try
                                    result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of System.Collections.Generic.IDictionary(Of String, ModelStateEntry))(responseData_, _settings.Value)
                                Catch exception_ As System.Exception
                                    Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                End Try
                                Throw New YkkClientException(Of System.Collections.Generic.IDictionary(Of String, ModelStateEntry))("Bad Request", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, result_, Nothing)
                            Else
                                If status_ = "401" Then
                                    Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                    Dim result_ = Nothing
                                    Try
                                        result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of ObjectResult)(responseData_, _settings.Value)
                                    Catch exception_ As System.Exception
                                        Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                    End Try
                                    Throw New YkkClientException(Of ObjectResult)("Unauthorized", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, result_, Nothing)
                                Else
                                    If status_ <> "200" AndAlso status_ <> "204" Then
                                        Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                        Throw New YkkClientException("The HTTP status code of the response was not expected (" & CInt(Math.Truncate(response_.StatusCode)) & ").", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, Nothing)
                                    End If
                                End If
                            End If
                        End If

                        Return Nothing
                    Finally
                        If response_ IsNot Nothing Then
                            response_.Dispose()
                        End If
                    End Try
                End Using
            Finally
                If client_ IsNot Nothing Then
                    client_.Dispose()
                End If
            End Try
        End Function


        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        Public Function GetAllAdressAsync(ByVal page As Integer, ByVal pagesize As Integer) As System.Threading.Tasks.Task(Of System.Collections.Generic.ICollection(Of APICustomerAdress))
            Return GetAllAdressAsync(page, pagesize, System.Threading.CancellationToken.None)
        End Function

        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        ''' <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        Public Async Function GetAllAdressAsync(ByVal page As Integer, ByVal pagesize As Integer, ByVal cancellationToken As System.Threading.CancellationToken) As System.Threading.Tasks.Task(Of System.Collections.Generic.ICollection(Of APICustomerAdress))
            'INSTANT VB WARNING: VB does not allow comparing non-nullable value types with 'null' - they are never equal to 'null':
            'ORIGINAL LINE: if (page == null)
            If IsNothing(page) Then
                Throw New System.ArgumentNullException("page")
            End If

            'INSTANT VB WARNING: VB does not allow comparing non-nullable value types with 'null' - they are never equal to 'null':
            'ORIGINAL LINE: if (pagesize == null)
            If IsNothing(pagesize) Then
                Throw New System.ArgumentNullException("pagesize")
            End If

            Dim urlBuilder_ = New System.Text.StringBuilder()
            urlBuilder_.Append(If(BaseUrl IsNot Nothing, BaseUrl.TrimEnd("/"c), String.Empty)).Append("/api/CustomerAdress/GetAllAdress/{page}/{pagesize}")
            urlBuilder_.Replace("{page}", System.Uri.EscapeDataString(ConvertToString(page, System.Globalization.CultureInfo.InvariantCulture)))
            urlBuilder_.Replace("{pagesize}", System.Uri.EscapeDataString(ConvertToString(pagesize, System.Globalization.CultureInfo.InvariantCulture)))

            Dim client_ = New System.Net.Http.HttpClient()
            Try
                Using request_ = New System.Net.Http.HttpRequestMessage()

                    request_.Method = New System.Net.Http.HttpMethod("GET")
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"))

                    PrepareRequest(client_, request_, urlBuilder_)
                    Dim url_ = urlBuilder_.ToString()
                    request_.RequestUri = New System.Uri(url_, System.UriKind.RelativeOrAbsolute)
                    PrepareRequest(client_, request_, url_)

                    Dim response_ = Await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(False)
                    Try
                        Dim headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, Function(h_) h_.Key, Function(h_) h_.Value)
                        If response_.Content IsNot Nothing AndAlso response_.Content.Headers IsNot Nothing Then
                            For Each item_ İn response_.Content.Headers
                                headers_(item_.Key) = item_.Value
                            Next item_
                        End If

                        ProcessResponse(client_, response_)

                        Dim status_ = CInt(Math.Truncate(response_.StatusCode)).ToString()
                        If status_ = "400" Then
                            Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                            Throw New YkkClientException("Bad Request", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, Nothing)
                        Else
                            If status_ = "401" Then
                                Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                Dim result_ = Nothing
                                Try
                                    result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of ObjectResult)(responseData_, _settings.Value)
                                Catch exception_ As System.Exception
                                    Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                End Try
                                Throw New YkkClientException(Of ObjectResult)("Unauthorized", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, result_, Nothing)
                            Else
                                If status_ = "404" Then
                                    Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                    Throw New YkkClientException("Not Found", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, Nothing)
                                Else
                                    If status_ = "200" Then
                                        Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                        Dim result_ = Nothing
                                        Try
                                            result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of System.Collections.Generic.ICollection(Of APICustomerAdress))(responseData_, _settings.Value)
                                            Return result_
                                        Catch exception_ As System.Exception
                                            Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                        End Try
                                    Else
                                        If status_ <> "200" AndAlso status_ <> "204" Then
                                            Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                            Throw New YkkClientException("The HTTP status code of the response was not expected (" & CInt(Math.Truncate(response_.StatusCode)) & ").", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, Nothing)
                                        End If
                                    End If
                                End If
                            End If
                        End If

                        Return Nothing
                    Finally
                        If response_ IsNot Nothing Then
                            response_.Dispose()
                        End If
                    End Try
                End Using
            Finally
                If client_ IsNot Nothing Then
                    client_.Dispose()
                End If
            End Try
        End Function


        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        Public Function GetMappedProductsAsync(ByVal customerProductCode As String, ByVal page? As Integer, ByVal pagesize? As Integer) As System.Threading.Tasks.Task(Of System.Collections.Generic.ICollection(Of APICUSTOMERSPRODUCT))
            Return GetMappedProductsAsync(customerProductCode, page, pagesize, System.Threading.CancellationToken.None)
        End Function


        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        ''' <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        Public Async Function GetMappedProductsAsync(ByVal customerProductCode As String, ByVal page? As Integer, ByVal pagesize? As Integer, ByVal cancellationToken As System.Threading.CancellationToken) As System.Threading.Tasks.Task(Of System.Collections.Generic.ICollection(Of APICUSTOMERSPRODUCT))
            Dim urlBuilder_ = New System.Text.StringBuilder()
            urlBuilder_.Append(If(BaseUrl IsNot Nothing, BaseUrl.TrimEnd("/"c), String.Empty)).Append("/api/CustomersProduct/GetMappedProducts?")
            If customerProductCode IsNot Nothing Then
                urlBuilder_.Append("customerProductCode=").Append(System.Uri.EscapeDataString(ConvertToString(customerProductCode, System.Globalization.CultureInfo.InvariantCulture))).Append("&")
            End If
            If page IsNot Nothing Then
                urlBuilder_.Append("page=").Append(System.Uri.EscapeDataString(ConvertToString(page, System.Globalization.CultureInfo.InvariantCulture))).Append("&")
            End If
            If pagesize IsNot Nothing Then
                urlBuilder_.Append("pagesize=").Append(System.Uri.EscapeDataString(ConvertToString(pagesize, System.Globalization.CultureInfo.InvariantCulture))).Append("&")
            End If
            urlBuilder_.Length -= 1

            Dim client_ = New System.Net.Http.HttpClient()
            Try
                Using request_ = New System.Net.Http.HttpRequestMessage()

                    request_.Method = New System.Net.Http.HttpMethod("GET")
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"))

                    PrepareRequest(client_, request_, urlBuilder_)
                    Dim url_ = urlBuilder_.ToString()
                    request_.RequestUri = New System.Uri(url_, System.UriKind.RelativeOrAbsolute)
                    PrepareRequest(client_, request_, url_)

                    Dim response_ = Await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(False)
                    Try
                        Dim headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, Function(h_) h_.Key, Function(h_) h_.Value)
                        If response_.Content IsNot Nothing AndAlso response_.Content.Headers IsNot Nothing Then
                            For Each item_ İn response_.Content.Headers
                                headers_(item_.Key) = item_.Value
                            Next item_
                        End If

                        ProcessResponse(client_, response_)

                        Dim status_ = CInt(Math.Truncate(response_.StatusCode)).ToString()
                        If status_ = "400" Then
                            Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                            Dim result_ = Nothing
                            Try
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of System.Collections.Generic.IDictionary(Of String, ModelStateEntry))(responseData_, _settings.Value)
                            Catch exception_ As System.Exception
                                Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                            End Try
                            Throw New YkkClientException(Of System.Collections.Generic.IDictionary(Of String, ModelStateEntry))("Bad Request", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, result_, Nothing)
                        Else
                            If status_ = "401" Then
                                Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                Dim result_ = Nothing
                                Try
                                    result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of ObjectResult)(responseData_, _settings.Value)
                                Catch exception_ As System.Exception
                                    Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                End Try
                                Throw New YkkClientException(Of ObjectResult)("Unauthorized", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, result_, Nothing)
                            Else
                                If status_ = "404" Then
                                    Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                    Throw New YkkClientException("Not Found", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, Nothing)
                                Else
                                    If status_ = "200" Then
                                        Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                        Dim result_ = Nothing
                                        Try
                                            result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of System.Collections.Generic.ICollection(Of APICUSTOMERSPRODUCT))(responseData_, _settings.Value)
                                            Return result_
                                        Catch exception_ As System.Exception
                                            Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                        End Try
                                    Else
                                        If status_ <> "200" AndAlso status_ <> "204" Then
                                            Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                            Throw New YkkClientException("The HTTP status code of the response was not expected (" & CInt(Math.Truncate(response_.StatusCode)) & ").", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, Nothing)
                                        End If
                                    End If
                                End If
                            End If
                        End If

                        Return Nothing
                    Finally
                        If response_ IsNot Nothing Then
                            response_.Dispose()
                        End If
                    End Try
                End Using
            Finally
                If client_ IsNot Nothing Then
                    client_.Dispose()
                End If
            End Try
        End Function


        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        Public Function PostOrderAsync(ByVal form As APIOrder) As System.Threading.Tasks.Task(Of String)
            Return PostOrderAsync(form, System.Threading.CancellationToken.None)
        End Function

        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        ''' <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        Public Async Function PostOrderAsync(ByVal form As APIOrder, ByVal cancellationToken As System.Threading.CancellationToken) As System.Threading.Tasks.Task(Of String)
            Dim urlBuilder_ = New System.Text.StringBuilder()
            urlBuilder_.Append(If(BaseUrl IsNot Nothing, BaseUrl.TrimEnd("/"c), String.Empty)).Append("/api/Order/PostOrder")

            Dim client_ = New System.Net.Http.HttpClient()
            Try
                Using request_ = New System.Net.Http.HttpRequestMessage()
                    Dim content_ = New System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(form, _settings.Value))
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json")
                    request_.Content = content_
                    request_.Method = New System.Net.Http.HttpMethod("POST")
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"))

                    PrepareRequest(client_, request_, urlBuilder_)
                    Dim url_ = urlBuilder_.ToString()
                    request_.RequestUri = New System.Uri(url_, System.UriKind.RelativeOrAbsolute)
                    PrepareRequest(client_, request_, url_)

                    Dim response_ = Await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(False)
                    Try
                        Dim headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, Function(h_) h_.Key, Function(h_) h_.Value)
                        If response_.Content IsNot Nothing AndAlso response_.Content.Headers IsNot Nothing Then
                            For Each item_ İn response_.Content.Headers
                                headers_(item_.Key) = item_.Value
                            Next item_
                        End If

                        ProcessResponse(client_, response_)

                        Dim status_ = CInt(Math.Truncate(response_.StatusCode)).ToString()
                        If status_ = "400" Then
                            Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                            Dim result_ = Nothing
                            Try
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of System.Collections.Generic.IDictionary(Of String, ModelStateEntry))(responseData_, _settings.Value)
                            Catch exception_ As System.Exception
                                Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                            End Try
                            Throw New YkkClientException(Of System.Collections.Generic.IDictionary(Of String, ModelStateEntry))("Bad Request", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, result_, Nothing)
                        Else
                            If status_ = "401" Then
                                Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                Dim result_ = Nothing
                                Try
                                    result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of ObjectResult)(responseData_, _settings.Value)
                                Catch exception_ As System.Exception
                                    Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                End Try
                                Throw New YkkClientException(Of ObjectResult)("Unauthorized", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, result_, Nothing)
                            Else
                                If status_ = "200" Then
                                    Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                    Dim result_ = Nothing
                                    Try
                                        result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of String)(responseData_, _settings.Value)
                                        Return result_
                                    Catch exception_ As System.Exception
                                        Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                    End Try
                                Else
                                    If status_ <> "200" AndAlso status_ <> "204" Then
                                        Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                        Throw New YkkClientException("The HTTP status code of the response was not expected (" & CInt(Math.Truncate(response_.StatusCode)) & ").", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, Nothing)
                                    End If
                                End If
                            End If
                        End If

                        Return Nothing
                    Finally
                        If response_ IsNot Nothing Then
                            response_.Dispose()
                        End If
                    End Try
                End Using
            Finally
                If client_ IsNot Nothing Then
                    client_.Dispose()
                End If
            End Try
        End Function


        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        Public Function GetOrderAsync(ByVal orderCodes As System.Collections.Generic.IEnumerable(Of String), ByVal orderStartDate? As System.DateTimeOffset, ByVal orderEndDate? As System.DateTimeOffset, ByVal requestDateStartDate? As System.DateTimeOffset, ByVal requestDateEndDate? As System.DateTimeOffset) As System.Threading.Tasks.Task(Of System.Collections.Generic.ICollection(Of APIOrderDetailResult))
            Return GetOrderAsync(orderCodes, orderStartDate, orderEndDate, requestDateStartDate, requestDateEndDate, System.Threading.CancellationToken.None)
        End Function


        ''' <returns>Success</returns>
        ''' <exception cref="YkkClientException">A server side error occurred.</exception>
        ''' <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        Public Async Function GetOrderAsync(ByVal orderCodes As System.Collections.Generic.IEnumerable(Of String), ByVal orderStartDate? As System.DateTimeOffset, ByVal orderEndDate? As System.DateTimeOffset, ByVal requestDateStartDate? As System.DateTimeOffset, ByVal requestDateEndDate? As System.DateTimeOffset, ByVal cancellationToken As System.Threading.CancellationToken) As System.Threading.Tasks.Task(Of System.Collections.Generic.ICollection(Of APIOrderDetailResult))
            Dim urlBuilder_ = New System.Text.StringBuilder()
            urlBuilder_.Append(If(BaseUrl IsNot Nothing, BaseUrl.TrimEnd("/"c), String.Empty)).Append("/api/Order/GetOrder?")
            If orderCodes IsNot Nothing Then
                For Each item_ İn orderCodes
                    urlBuilder_.Append("orderCodes=").Append(System.Uri.EscapeDataString(ConvertToString(item_, System.Globalization.CultureInfo.InvariantCulture))).Append("&")
                Next item_
            End If
            If orderStartDate IsNot Nothing Then
                urlBuilder_.Append("orderStartDate=").Append(System.Uri.EscapeDataString(orderStartDate.Value.ToString("s", System.Globalization.CultureInfo.InvariantCulture))).Append("&")
            End If
            If orderEndDate IsNot Nothing Then
                urlBuilder_.Append("orderEndDate=").Append(System.Uri.EscapeDataString(orderEndDate.Value.ToString("s", System.Globalization.CultureInfo.InvariantCulture))).Append("&")
            End If
            If requestDateStartDate IsNot Nothing Then
                urlBuilder_.Append("requestDateStartDate=").Append(System.Uri.EscapeDataString(requestDateStartDate.Value.ToString("s", System.Globalization.CultureInfo.InvariantCulture))).Append("&")
            End If
            If requestDateEndDate IsNot Nothing Then
                urlBuilder_.Append("requestDateEndDate=").Append(System.Uri.EscapeDataString(requestDateEndDate.Value.ToString("s", System.Globalization.CultureInfo.InvariantCulture))).Append("&")
            End If
            urlBuilder_.Length -= 1

            Dim client_ = New System.Net.Http.HttpClient()
            Try
                Using request_ = New System.Net.Http.HttpRequestMessage()

                    request_.Method = New System.Net.Http.HttpMethod("GET")
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"))

                    PrepareRequest(client_, request_, urlBuilder_)
                    Dim url_ = urlBuilder_.ToString()
                    request_.RequestUri = New System.Uri(url_, System.UriKind.RelativeOrAbsolute)
                    PrepareRequest(client_, request_, url_)

                    Dim response_ = Await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(False)
                    Try
                        Dim headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, Function(h_) h_.Key, Function(h_) h_.Value)
                        If response_.Content IsNot Nothing AndAlso response_.Content.Headers IsNot Nothing Then
                            For Each item_ İn response_.Content.Headers
                                headers_(item_.Key) = item_.Value
                            Next item_
                        End If

                        ProcessResponse(client_, response_)

                        Dim status_ = CInt(Math.Truncate(response_.StatusCode)).ToString()
                        If status_ = "400" Then
                            Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                            Dim result_ = Nothing
                            Try
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of System.Collections.Generic.IDictionary(Of String, ModelStateEntry))(responseData_, _settings.Value)
                            Catch exception_ As System.Exception
                                Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                            End Try
                            Throw New YkkClientException(Of System.Collections.Generic.IDictionary(Of String, ModelStateEntry))("Bad Request", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, result_, Nothing)
                        Else
                            If status_ = "401" Then
                                Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                Dim result_ = Nothing
                                Try
                                    result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of ObjectResult)(responseData_, _settings.Value)
                                Catch exception_ As System.Exception
                                    Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                End Try
                                Throw New YkkClientException(Of ObjectResult)("Unauthorized", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, result_, Nothing)
                            Else
                                If status_ = "200" Then
                                    Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                    Dim result_ = Nothing
                                    Try
                                        result_ = Newtonsoft.Json.JsonConvert.DeserializeObject(Of System.Collections.Generic.ICollection(Of APIOrderDetailResult))(responseData_, _settings.Value)
                                        Return result_
                                    Catch exception_ As System.Exception
                                        Throw New YkkClientException("Could not deserialize the response body.", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, exception_)
                                    End Try
                                Else
                                    If status_ <> "200" AndAlso status_ <> "204" Then
                                        Dim responseData_ = If(response_.Content İs Nothing, Nothing, Await response_.Content.ReadAsStringAsync().ConfigureAwait(False))
                                        Throw New YkkClientException("The HTTP status code of the response was not expected (" & CInt(Math.Truncate(response_.StatusCode)) & ").", CInt(Math.Truncate(response_.StatusCode)), responseData_, headers_, Nothing)
                                    End If
                                End If
                            End If
                        End If

                        Return Nothing
                    Finally
                        If response_ IsNot Nothing Then
                            response_.Dispose()
                        End If
                    End Try
                End Using
            Finally
                If client_ IsNot Nothing Then
                    client_.Dispose()
                End If
            End Try
        End Function

        Private Function ConvertToString(ByVal value As Object, ByVal cultureInfo As System.Globalization.CultureInfo) As String
            If TypeOf value Is System.Enum Then
                Dim name As String = System.Enum.GetName(value.GetType(), value)
                If name IsNot Nothing Then
                    Dim field = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name)
                    If field IsNot Nothing Then
                        Dim attribute = TryCast(System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field, GetType(System.Runtime.Serialization.EnumMemberAttribute)), System.Runtime.Serialization.EnumMemberAttribute)
                        If attribute IsNot Nothing Then
                            Return attribute.Value
                        End If
                    End If
                End If
            ElseIf TypeOf value Is Boolean Then
                Return System.Convert.ToString(value, cultureInfo).ToLowerInvariant()
            ElseIf TypeOf value Is Byte() Then
                Return System.Convert.ToBase64String(DirectCast(value, Byte()))
            ElseIf value IsNot Nothing AndAlso value.GetType().IsArray Then
                Dim array = System.Linq.Enumerable.OfType(Of Object)(DirectCast(value, System.Array))
                Return String.Join(",", System.Linq.Enumerable.Select(array, Function(o) ConvertToString(o, cultureInfo)))
            End If

            Return System.Convert.ToString(value, cultureInfo)
        End Function
    End Class



    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class LoginModel
        <Newtonsoft.Json.JsonProperty("username", Required:=Newtonsoft.Json.Required.Always)>
        <System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings:=True)>
        Public Property Username() As String

        <Newtonsoft.Json.JsonProperty("password", Required:=Newtonsoft.Json.Required.Always)>
        <System.ComponentModel.DataAnnotations.Required>
        <System.ComponentModel.DataAnnotations.StringLength(Integer.MaxValue, MinimumLength:=6)>
        Public Property Password() As String

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As LoginModel
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of LoginModel)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class ModelStateEntry
        <Newtonsoft.Json.JsonProperty("rawValue", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property RawValue() As Object

        <Newtonsoft.Json.JsonProperty("attemptedValue", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property AttemptedValue() As String

        <Newtonsoft.Json.JsonProperty("errors", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Errors() As System.Collections.Generic.ICollection(Of ModelError)

        <Newtonsoft.Json.JsonProperty("validationState", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property ValidationState() As ModelStateEntryValidationState?

        <Newtonsoft.Json.JsonProperty("isContainerNode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property IsContainerNode() As Boolean?

        <Newtonsoft.Json.JsonProperty("children", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Children() As System.Collections.Generic.ICollection(Of ModelStateEntry)

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As ModelStateEntry
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of ModelStateEntry)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class ModelError
        <Newtonsoft.Json.JsonProperty("exception", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Exception() As Object

        <Newtonsoft.Json.JsonProperty("errorMessage", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property ErrorMessage() As String

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As ModelError
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of ModelError)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class ObjectResult
        <Newtonsoft.Json.JsonProperty("value", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Value() As Object

        <Newtonsoft.Json.JsonProperty("formatters", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Formatters() As System.Collections.Generic.ICollection(Of Object)

        <Newtonsoft.Json.JsonProperty("contentTypes", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property ContentTypes() As System.Collections.Generic.ICollection(Of String)

        <Newtonsoft.Json.JsonProperty("declaredType", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property DeclaredType() As String

        <Newtonsoft.Json.JsonProperty("statusCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property StatusCode() As Integer?

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As ObjectResult
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of ObjectResult)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class APICustomerAdress
        <Newtonsoft.Json.JsonProperty("deliveryAdress", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property DeliveryAdress() As String

        <Newtonsoft.Json.JsonProperty("deliveryName", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property DeliveryName() As String

        <Newtonsoft.Json.JsonProperty("deliveryCode1", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property DeliveryCode1() As String

        <Newtonsoft.Json.JsonProperty("deliveryCode2", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property DeliveryCode2() As String

        <Newtonsoft.Json.JsonProperty("transportationCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property TransportationCode() As String

        <Newtonsoft.Json.JsonProperty("countryCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property CountryCode() As String

        <Newtonsoft.Json.JsonProperty("registerdate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Registerdate() As Integer?

        <Newtonsoft.Json.JsonProperty("registertime", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Registertime() As Integer?

        <Newtonsoft.Json.JsonProperty("lastupdatedate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Lastupdatedate() As Integer?

        <Newtonsoft.Json.JsonProperty("lastupdatetime", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Lastupdatetime() As Integer?

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As APICustomerAdress
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of APICustomerAdress)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class APICUSTOMERSPRODUCT
        <Newtonsoft.Json.JsonProperty("totalCount", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property TotalCount() As Integer?

        <Newtonsoft.Json.JsonProperty("customersProductCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property CustomersProductCode() As String

        <Newtonsoft.Json.JsonProperty("itemcode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Itemcode() As String

        <Newtonsoft.Json.JsonProperty("itemname", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Itemname() As String

        <Newtonsoft.Json.JsonProperty("producttype", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Producttype() As APICUSTOMERSPRODUCTProducttype?

        <Newtonsoft.Json.JsonProperty("unit", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Unit() As APICUSTOMERSPRODUCTUnit?

        <Newtonsoft.Json.JsonProperty("lenght", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Lenght() As String

        <Newtonsoft.Json.JsonProperty("color", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Color() As String

        <Newtonsoft.Json.JsonProperty("quantityunitcode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Quantityunitcode() As String

        <Newtonsoft.Json.JsonProperty("registerdate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Registerdate() As Integer?

        <Newtonsoft.Json.JsonProperty("registertime", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Registertime() As Integer?

        <Newtonsoft.Json.JsonProperty("lastupdatedate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Lastupdatedate() As Integer?

        <Newtonsoft.Json.JsonProperty("lastupdatetime", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Lastupdatetime() As Integer?

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As APICUSTOMERSPRODUCT
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of APICUSTOMERSPRODUCT)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class APIOrder
        <Newtonsoft.Json.JsonProperty("deliverCode1", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        <System.ComponentModel.DataAnnotations.StringLength(6)>
        Public Property DeliverCode1() As String

        <Newtonsoft.Json.JsonProperty("deliverCode2", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        <System.ComponentModel.DataAnnotations.StringLength(3)>
        Public Property DeliverCode2() As String

        <Newtonsoft.Json.JsonProperty("buyerCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        <System.ComponentModel.DataAnnotations.StringLength(6)>
        Public Property BuyerCode() As String

        <Newtonsoft.Json.JsonProperty("purchasecontractno", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        <System.ComponentModel.DataAnnotations.StringLength(30)>
        Public Property Purchasecontractno() As String

        <Newtonsoft.Json.JsonProperty("timeConvention", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property TimeConvention() As APIOrderTimeConvention?

        <Newtonsoft.Json.JsonProperty("requestDate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property RequestDate() As System.DateTimeOffset?

        <Newtonsoft.Json.JsonProperty("sampleOrder", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property SampleOrder() As Boolean?

        <Newtonsoft.Json.JsonProperty("noCommercial", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property NoCommercial() As Boolean?

        <Newtonsoft.Json.JsonProperty("completeDelivery", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property CompleteDelivery() As Boolean?

        <Newtonsoft.Json.JsonProperty("orderComment", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        <System.ComponentModel.DataAnnotations.StringLength(105)>
        Public Property OrderComment() As String

        <Newtonsoft.Json.JsonProperty("apiOrderItems", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property ApiOrderItems() As System.Collections.Generic.ICollection(Of APIOrderItems)

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As APIOrder
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of APIOrder)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class APIOrderItems
        <Newtonsoft.Json.JsonProperty("productCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        <System.ComponentModel.DataAnnotations.StringLength(7)>
        Public Property ProductCode() As String

        <Newtonsoft.Json.JsonProperty("customersProductCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        <System.ComponentModel.DataAnnotations.StringLength(15)>
        Public Property CustomersProductCode() As String

        <Newtonsoft.Json.JsonProperty("count", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Count() As Integer?

        <Newtonsoft.Json.JsonProperty("color", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        <System.ComponentModel.DataAnnotations.StringLength(12)>
        Public Property Color() As String

        <Newtonsoft.Json.JsonProperty("length", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        <System.ComponentModel.DataAnnotations.StringLength(6)>
        Public Property Length() As String

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As APIOrderItems
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of APIOrderItems)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class APIOrderDetailResult
        <Newtonsoft.Json.JsonProperty("purchaseOrderNo", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property PurchaseOrderNo() As String

        <Newtonsoft.Json.JsonProperty("purchaseContractNo", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property PurchaseContractNo() As String

        <Newtonsoft.Json.JsonProperty("orderStatus", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property OrderStatus() As String

        <Newtonsoft.Json.JsonProperty("buyerCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property BuyerCode() As String

        <Newtonsoft.Json.JsonProperty("priceListVersion", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property PriceListVersion() As String

        <Newtonsoft.Json.JsonProperty("customerCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property CustomerCode() As String

        <Newtonsoft.Json.JsonProperty("completeDelivery", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property CompleteDelivery() As Boolean?

        <Newtonsoft.Json.JsonProperty("deliveryCode1", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property DeliveryCode1() As String

        <Newtonsoft.Json.JsonProperty("deliveryCode2", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property DeliveryCode2() As String

        <Newtonsoft.Json.JsonProperty("noCommercial", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property NoCommercial() As Boolean?

        <Newtonsoft.Json.JsonProperty("timeConvention", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property TimeConvention() As APIOrderDetailResultTimeConvention?

        <Newtonsoft.Json.JsonProperty("sampleOrder", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property SampleOrder() As Boolean?

        <Newtonsoft.Json.JsonProperty("currencyCode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property CurrencyCode() As String

        <Newtonsoft.Json.JsonProperty("itemDetailCount", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property ItemDetailCount() As Integer?

        <Newtonsoft.Json.JsonProperty("apiOrderItemsDetailResults", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property ApiOrderItemsDetailResults() As System.Collections.Generic.ICollection(Of APIOrderItemsDetailResult)

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As APIOrderDetailResult
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of APIOrderDetailResult)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Partial Public Class APIOrderItemsDetailResult
        <Newtonsoft.Json.JsonProperty("length", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Length() As String

        <Newtonsoft.Json.JsonProperty("color", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Color() As String

        <Newtonsoft.Json.JsonProperty("leadTime", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property LeadTime() As System.DateTimeOffset?

        <Newtonsoft.Json.JsonProperty("orderarrangesubno", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Orderarrangesubno() As Integer?

        <Newtonsoft.Json.JsonProperty("allocatecontrolcode", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Allocatecontrolcode() As String

        <Newtonsoft.Json.JsonProperty("allocatecontrolsubno", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Allocatecontrolsubno() As Integer?

        <Newtonsoft.Json.JsonProperty("orderallocatedate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Orderallocatedate() As System.DateTimeOffset?

        <Newtonsoft.Json.JsonProperty("allocateconfirmdate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Allocateconfirmdate() As System.DateTimeOffset?

        <Newtonsoft.Json.JsonProperty("allocatecontrolquantity", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Allocatecontrolquantity() As Double?

        <Newtonsoft.Json.JsonProperty("actualtimeofallocatefinish", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Actualtimeofallocatefinish() As System.DateTimeOffset?

        <Newtonsoft.Json.JsonProperty("estimatedtimeofallocatefinish", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Estimatedtimeofallocatefinish() As System.DateTimeOffset?

        <Newtonsoft.Json.JsonProperty("packingcompletedate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Packingcompletedate() As Integer?

        <Newtonsoft.Json.JsonProperty("packingcompletequantity", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Packingcompletequantity() As Double?

        <Newtonsoft.Json.JsonProperty("requestallocatecompletedate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Requestallocatecompletedate() As System.DateTimeOffset?

        <Newtonsoft.Json.JsonProperty("packingcompletetime", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Packingcompletetime() As System.DateTimeOffset?

        <Newtonsoft.Json.JsonProperty("packinglistno", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Packinglistno() As String

        <Newtonsoft.Json.JsonProperty("salesdate", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Salesdate() As Integer?

        <Newtonsoft.Json.JsonProperty("invoiceno", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Invoiceno() As String

        <Newtonsoft.Json.JsonProperty("salesquantity", Required:=Newtonsoft.Json.Required.Default, NullValueHandling:=Newtonsoft.Json.NullValueHandling.Ignore)>
        Public Property Salesquantity() As Double?

        Public Function ToJson() As String
            Return Newtonsoft.Json.JsonConvert.SerializeObject(Me)
        End Function

        Public Shared Function FromJson(ByVal data As String) As APIOrderItemsDetailResult
            Return Newtonsoft.Json.JsonConvert.DeserializeObject(Of APIOrderItemsDetailResult)(data)
        End Function

    End Class

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Public Enum ModelStateEntryValidationState
        _0 = 0

        _1 = 1

        _2 = 2

        _3 = 3

    End Enum

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Public Enum APICUSTOMERSPRODUCTProducttype
        _10 = 10

        _20 = 20

        _30 = 30

    End Enum

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Public Enum APICUSTOMERSPRODUCTUnit
        _5 = 5

        _10 = 10

        _20 = 20

        _30 = 30

    End Enum

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Public Enum APIOrderTimeConvention
        _1 = 1

        _2 = 2

    End Enum

    <System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.2.0 (Newtonsoft.Json v11.0.0.0)")>
    Public Enum APIOrderDetailResultTimeConvention
        _1 = 1

        _2 = 2

    End Enum

    <System.CodeDom.Compiler.GeneratedCode("NSwag", "12.0.5.0 (NJsonSchema v9.13.2.0 (Newtonsoft.Json v11.0.0.0))")>
    Partial Public Class YkkClientException
        Inherits System.Exception

        Private privateStatusCode As Integer
        Public Property StatusCode() As Integer
            Get
                Return privateStatusCode
            End Get
            Private Set(ByVal value As Integer)
                privateStatusCode = value
            End Set
        End Property

        Private privateResponse As String
        Public Property Response() As String
            Get
                Return privateResponse
            End Get
            Private Set(ByVal value As String)
                privateResponse = value
            End Set
        End Property

        Private privateHeaders As System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.IEnumerable(Of String))
        Public Property Headers() As System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.IEnumerable(Of String))
            Get
                Return privateHeaders
            End Get
            Private Set(ByVal value As System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.IEnumerable(Of String)))
                privateHeaders = value
            End Set
        End Property

        Public Sub New(ByVal message As String, ByVal statusCode As Integer, ByVal response As String, ByVal headers As System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.IEnumerable(Of String)), ByVal innerException As System.Exception)
            MyBase.New(message & vbLf & vbLf & "Status: " & statusCode & vbLf & "Response: " & vbLf & response.Substring(0, If(response.Length >= 512, 512, response.Length)), innerException)
            Me.StatusCode = statusCode
            Me.Response = response
            Me.Headers = headers
        End Sub

        Public Overrides Function ToString() As String
            Return String.Format("HTTP Response: " & vbLf & vbLf & "{0}" & vbLf & vbLf & "{1}", Response, MyBase.ToString())
        End Function
    End Class

    <System.CodeDom.Compiler.GeneratedCode("NSwag", "12.0.5.0 (NJsonSchema v9.13.2.0 (Newtonsoft.Json v11.0.0.0))")>
    Partial Public Class YkkClientException(Of TResult)
        Inherits YkkClientException

        Private privateResult As TResult
        Public Overloads Property Result() As TResult
            Get
                Return privateResult
            End Get
            Private Set(ByVal value As TResult)
                privateResult = value
            End Set
        End Property

        Public Sub New(ByVal message As String, ByVal statusCode As Integer, ByVal response As String, ByVal headers As System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.IEnumerable(Of String)), ByVal result As TResult, ByVal innerException As System.Exception)
            MyBase.New(message, statusCode, response, headers, innerException)
            Me.Result = result
        End Sub
    End Class

#Enable Warning
End Namespace